### ISSUE TITLE
Show non-english label if no English label exists

### ISSUE THREAD

**Issue by nichtich** [WDscholia/scholia#1]
At least for works as not everything is published in English and translating publication titles seems wrong. Unfortunately I don't know how to support _any_ language. I stumbled upon this because of https://www.wikidata.org/wiki/Q27044176. To support at least some other languages change

```
SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } 
```

to

```
SERVICE wikibase:label { bd:serviceParam wikibase:language "en,fr,de,ru,es,zh,jp". } 
```

and/or try to get the title via title propert https://www.wikidata.org/wiki/Property:P1476.

**Comment by fnielsen** [comment]
Danke for the suggestion. I have added the language fallbacks you suggested. This is presently only for the author pages. There may be a number of other pages where fallbacks could be nice.

**Comment by fnielsen** [comment]
For instance, https://tools.wmflabs.org/scholia/author/Q15303972 shows "Wikidata als Universalbibliographie: ein Kommentar"

**Comment by Daniel-Mietchen** [comment]
I think this is actually implemented for all aspects now, but have not checked them all yet.
