### ISSUE TITLE
Missing Topic button

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1008]
On some pages, the Topic button is missing, e.g. currently at
https://tools.wmflabs.org/scholia/disease/Q41112 .

**Comment by fnielsen** [comment]
Hmmm... I see the topic button at https://tools.wmflabs.org/scholia/disease/Q41112. I wonder what that error was.

**Comment by Daniel-Mietchen** [comment]
I see it now as well. That was not the only page where I had noticed this behavior, though, and I suspect it may have something to do with JavaScript being timed out before it gets to the point when it is supposed to render such buttons.

**Comment by fnielsen** [comment]
I suppose there could be something like "Too many requests" perhaps. Maybe the debug information with F12 (in Firefox) can show something.

**Comment by Daniel-Mietchen** [comment]
I just had this again at https://tools.wmflabs.org/scholia/organization/Q319239 . 
Screenshot at https://commons.wikimedia.org/wiki/File:Screenshot_of_Scholia_organization_profile_for_Tel_Aviv_University_as_of_10_January_2020.png .
Not sure what precisely I should look for when debugging &mdash; a screenshot is attached.
<img width="1440" alt="Screen Shot 2020-01-10 at 20 10 52" src="https://user-images.githubusercontent.com/465923/72196347-76b01500-33e5-11ea-8f8c-208aa3b994ce.png">

**Comment by fnielsen** [comment]
I do not understand the Tel Aviv case. There is no work that has Tel Aviv University as topic: https://tools.wmflabs.org/scholia/topic/Q319239 so that is why the topic button does not show.

**Comment by carlinmack** [comment]
I think there is an outstanding bug here, which is the converse: There is no disease button on the topic page

- https://scholia.toolforge.org/topic/Q41112
- https://scholia.toolforge.org/disease/Q41112

**Comment by carlinmack** [comment]
This was already noted in #463, this can be closed
