### ISSUE TITLE
Migration to 2020 Kubernetes 

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1013]
https://wikitech.wikimedia.org/wiki/News/2020_Kubernetes_cluster_migration#What_should_I_do?

**Comment by nunogit** [comment]
Related - Dockerization is a first step https://github.com/fnielsen/scholia/issues/966

**Comment by fnielsen** [comment]
No, dockerization is unrelated. 2020 Kubernetes is related to Toolforge

**Comment by nunogit** [comment]
Yes, I miss read it. They already use Kubernetes. They are updating.
Docker is one of the underlying technologies in Kubernetes. In this sense, I thought we could better "surf this wave", but the wave was already there.

**Comment by fnielsen** [comment]
Webservice migrate as stated on https://wikitech.wikimedia.org/w/index.php?title=News/2020_Kubernetes_cluster_migration&oldid=1854854#Manually_migrate_a_webservice_to_the_new_cluster does not work. it generates an error https://wikitech.wikimedia.org/w/index.php?title=Talk:News/2020_Kubernetes_cluster_migration&diff=1856336&oldid=1850278

It is possible to go back to older documentation at https://wikitech.wikimedia.org/w/index.php?title=News/2020_Kubernetes_cluster_migration&oldid=1851901#Manually_migrate_a_webservice_to_the_new_cluster  This allows us to change to the new system. However, there is a failure. The first failure was related to lxml import #1050. A commit has presumably fixed that. A restart of the server with the commit now results in another failure with an unclear nature. the starting process restarts at `mounting /data/project/scholia/www/python/src/app.py on /scholia` No further error message seems available.

**Comment by fnielsen** [comment]
A Phabricator task: https://phabricator.wikimedia.org/T245814

**Comment by fnielsen** [comment]
Apparently fixed to Python3.7.

**Comment by Daniel-Mietchen** [comment]
According to [Nova Resource:Tools.scholia/SAL](https://wikitech.wikimedia.org/w/index.php?title=Nova_Resource:Tools.scholia/SAL&oldid=1858011), this happened on 2020-02-28.
