### ISSUE TITLE
Page title should contain subject identifier/name/title/label

### ISSUE THREAD

**Issue by nunogit** [WDscholia/scholia#1041]
Currently, when opening a page (or if accessing a page directly) one can easily lose track of the subject:

![image](https://user-images.githubusercontent.com/2419453/74180087-1956f000-4c3f-11ea-9937-5ad4e32c2922.png)

The suggestion would be to add the identifier/name/title/label to the title.

### **EDIT 1**
Some pages already display this way:

![image](https://user-images.githubusercontent.com/2419453/74181396-89667580-4c41-11ea-9c1d-9c8988d7a092.png)

**Comment by fnielsen** [comment]
Currently it uses the MediaWiki API and take the English label. I suppose there could be a better fallback.

**Comment by carlinmack** [comment]
All aspects should have a title once #1548 is closed

**Comment by Daniel-Mietchen** [comment]
This is working now. Closing.
