### ISSUE TITLE
Crash of webservice 

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1062]
https://tools.wmflabs.org/scholia/ reports "503 Service Temporarily Unavailable". 

The uwsgi.log file states
```
SIGINT/SIGQUIT received...killing workers...
Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters

Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters

Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters

Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters

worker 1 buried after 1 seconds
worker 3 buried after 3 seconds
```

**Comment by fnielsen** [comment]
Trying to restart with `webservice --backend=kubernetes python3.7 restart`.

Maybe related to https://lists.wikimedia.org/pipermail/cloud-announce/2020-February/000260.html

**Comment by fnielsen** [comment]
WMF cloud team seems to be working on it.

**Comment by fnielsen** [comment]
https://tools.wmflabs.org/scholia/

**Comment by fnielsen** [comment]
A similar problem is back

**Comment by fnielsen** [comment]
Also tracked here: https://phabricator.wikimedia.org/T246523

**Comment by fnielsen** [comment]
A problem again :(

**Comment by fnielsen** [comment]
Restarted with `webservice --backend=kubernetes -m 1Gi python3.7 restart`

**Comment by nunogit** [comment]
@fnielsen is there a pattern on this? is it due to maintenance, memory?

**Comment by fnielsen** [comment]
I think it might be `show_author_random`. We need to disable that one. It might hit some memory ceil. https://grafana-labs.wikimedia.org/d/toolforge-k8s-namespace-resources/kubernetes-namespace-resources?orgId=1&var-namespace=tool-scholia&from=1583507623686&to=1583510443391

**Comment by Daniel-Mietchen** [comment]
I just added links to here and #1357 from [the wiki](https://github.com/WDscholia/scholia/wiki/Home/_compare/530d234e01eb8f5c9215ca5443e5987ae5b5e83d...90e3577f928cd40c3fafafdcee30c16942aa496d).

Closing here.
