### ISSUE TITLE
Add COVID-19 link to home page

### ISSUE THREAD

**Issue by pigsonthewing** [WDscholia/scholia#1071]
During the current emergency, it would be advantageous to have a link to 

https://tools.wmflabs.org/scholia/disease/Q84263196

on the home page, perhaps replacing, or alongside, the existing Zika virus link.

Consider also including related links, such as:

https://tools.wmflabs.org/scholia/topic/Q82069695

**Comment by nunogit** [comment]
The home page could actually be updated to work a bit like Wikipedia, where the front page could highlight important topics being discussed in the scientific community, Desirably this could be done automatically
