### ISSUE TITLE
Error running tox

### ISSUE THREAD

**Issue by fehrhart** [WDscholia/scholia#1096]
OS: Win10, Py 3.7.4, 

Friederike.Ehrhart@fhmlcogenwks017 MINGW64 ~/AppData/Local/Programs/Python/Python37-32/scholia (master)
$ tox -e flake8
GLOB sdist-make: C:\Users\friederike.ehrhart\AppData\Local\Programs\Python\Python37-32\scholia\setup.py
ERROR: invocation failed (exit code 1), logfile: C:\Users\friederike.ehrhart\AppData\Local\Programs\Python\Python37-32\scholia\.tox\log\GLOB-0.log
====================================================== log start ======================================================
running sdist
running egg_info
writing scholia.egg-info\PKG-INFO
writing dependency_links to scholia.egg-info\dependency_links.txt
writing requirements to scholia.egg-info\requires.txt
writing top-level names to scholia.egg-info\top_level.txt
package init file 'scholia\__init__.py' not found (or not a regular file)
reading manifest file 'scholia.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'scholia\_version.py'
writing manifest file 'scholia.egg-info\SOURCES.txt'
running check
copying files to scholia-0.2+136.g8f8e9b6.dirty...
copying scholia.egg-info\PKG-INFO -> scholia-0.2+136.g8f8e9b6.dirty\scholia.egg-info
copying scholia.egg-info\SOURCES.txt -> scholia-0.2+136.g8f8e9b6.dirty\scholia.egg-info
copying scholia.egg-info\dependency_links.txt -> scholia-0.2+136.g8f8e9b6.dirty\scholia.egg-info
copying scholia.egg-info\requires.txt -> scholia-0.2+136.g8f8e9b6.dirty\scholia.egg-info
copying scholia.egg-info\top_level.txt -> scholia-0.2+136.g8f8e9b6.dirty\scholia.egg-info
Writing scholia-0.2+136.g8f8e9b6.dirty\setup.cfg
UPDATING scholia-0.2+136.g8f8e9b6.dirty\scholia/_version.py
error: [WinError 2] The system cannot find the file specified: 'scholia-0.2+136.g8f8e9b6.dirty\\scholia/_version.py'

======================================================= log end =======================================================
ERROR: FAIL could not package project - v = InvocationError("'c:\\users\\friederike.ehrhart\\appdata\\local\\programs\\python\\python37-32\\python.exe' setup.py sdist --formats=zip --dist-dir 'C:\\Users\\friederike.ehrhart\\AppData\\Local\\Programs\\Python\\Python37-32\\scholia\\.tox\\dist'", 1)

**Comment by Daniel-Mietchen** [comment]
[Here](https://stackoverflow.com/questions/44884828/python-invocationerror-in-tox-running-py-test-and-coverage-test) is a StackOverflow ticket for the InvocationError, suggesting that tox.ini might need to be fixed.

**Comment by egonw** [comment]
@fehrhart, there have been some fixes to the tox setup earlier this year. Could you please try it once more to confirm the problem still exists?
