### ISSUE TITLE
Make individual panels individually accessible via some PID-based URL scheme

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1113]
I thought we had a ticket for this already but could not find one now, so just putting this here so that it's (back) on the radar.

**Comment by Daniel-Mietchen** [comment]
This is also relevant for externalizing SPARQL queries, as per #907 .

**Comment by carlinmack** [comment]
This was the original ticket https://github.com/WDscholia/scholia/issues/348

**Comment by Daniel-Mietchen** [comment]
Closing this as duplicate of #348.
