### ISSUE TITLE
H2 vs H3 headers

### ISSUE THREAD

**Issue by nunogit** [WDscholia/scholia#1128]
Many pages have H2 and H3 titles. 

In terms of UI, they are indistinguishable at plain sight. The CSS of each is very similar.
This raises the question if having h2 and h3 headers is on purpose or just not consistent.

Suggestions:
- If lack of consistency, make all headers H2
- Otherwise, make the difference more noticeable in CSS

eg.:
![image](https://user-images.githubusercontent.com/2419453/81732473-d4866380-9490-11ea-9462-7667d36f56f9.png)

Number of pages per year - **H3**
Venue statistics - **H2**

**Comment by Daniel-Mietchen** [comment]
I'd go for making the difference more pronounced.

**Comment by fnielsen** [comment]
Yes, they should be consistent. Aren't we using vanilla Bootstrap? h1 on the top. After that h2. Something h3, e.g., h2 on a citation section that have multiple table labeled with h3 headers.

**Comment by Daniel-Mietchen** [comment]
Perhaps @carlinmack has an opinion here?

**Comment by carlinmack** [comment]
Agree with the above, 
- make the difference more pronounced
- only use smaller ones if they have a corresponding larger heading above it. 

Imagine making a table of contents, you wouldn't naturally do
![image](https://user-images.githubusercontent.com/6676843/82236966-eb9ada80-9902-11ea-9af5-012f26ff2da8.png)
but you might do
![image](https://user-images.githubusercontent.com/6676843/82237056-0ec58a00-9903-11ea-91f4-b0d8db45fdf9.png)

**Comment by nunogit** [comment]
I dug a bit more into this. 
I find it strange that bootstrap has H2 and H3 so close in size.

So, the sizes in CSS for bootstrap are defined in rem. H2 is currently 2rem and H3 is 1.75. In pixels, this corresponds to H2 = 32px and H3 = 28px.

This is a very close size and, strangely, the bootstrap team has made this decision.
Anyway, I played a bit in jsfiddle with bootstrap and apparently, 1.5rem  (24px) size would be good for H3. 

http://jsfiddle.net/m26frngk/

Any suggestions?

**Comment by Daniel-Mietchen** [comment]
Looks good to me.

**Comment by carlinmack** [comment]
@Daniel-Mietchen #1168 fixed the size, #1492 validated they are appropriate. Anything else needed to be done in this issue?

**Comment by carlinmack** [comment]
Actually #1168 did nothing as it added invalid CSS to the stylesheet. Will redo the PR.

**Comment by carlinmack** [comment]
I believe this is closed now
