### ISSUE TITLE
Clean commented iframes

### ISSUE THREAD

**Issue by nunogit** [WDscholia/scholia#1170]
Clean commented iframes. This creates noise in iframe testing:

https://scholia.toolforge.org/author/Q18618629
 
![image](https://user-images.githubusercontent.com/2419453/86484541-bc2b1a80-bd56-11ea-89f3-7b66c886dd3e.png)

**Comment by yesidays** [comment]
Can I work this ticket?

**Comment by Daniel-Mietchen** [comment]
@yesidays Welcome and thanks for the suggestion. Sorry, hadn't seen this earlier. We are going to work on https://github.com/fnielsen/scholia/pull/907 today, which may well address the iframe issue as well.

So adding this to our hackathon to facilitate tracking.

**Comment by fnielsen** [comment]
I suppose we could just erase them?

**Comment by Daniel-Mietchen** [comment]
Yes

**Comment by DanielFLopez** [comment]
I was checking the code and I did not find comments in the HTML that included iframes

**Comment by Daniel-Mietchen** [comment]
Thanks for checking, @DanielFLopez . I also had a look and could not find any commented-out iframes.

What I did find was other commented-out functionality, e.g. as per https://github.com/WDscholia/scholia/blob/8721a45832695d8807270d8ee37c3c000523ef43/scholia/app/templates/author.html#L235 .

Will open a new ticket for that, so that this current one can be closed.

**Comment by Daniel-Mietchen** [comment]
That new issue is now up at https://github.com/WDscholia/scholia/issues/1514 . Closing.

**Comment by curibe** [comment]
@Daniel-Mietchen There is a commented iframe in [country.html](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/country.html) 
![image](https://user-images.githubusercontent.com/1589267/125988149-a9f069e2-4271-4c2d-8c17-876a07a7aec9.png)

**Comment by DanielFLopez** [comment]
I will check again, sorry
