### ISSUE TITLE
"Use" column in use aspect table should go to use aspects

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1192]
Items in "Most used" at https://scholia.toolforge.org/use/ typically go to topic aspect. They should go to "use" aspect

**Comment by Daniel-Mietchen** [comment]
Let me try to explain better what is meant here.

The page https://scholia.toolforge.org/use/ currently looks as follows:
![Screenshot 2021-11-01 at 21-22-43 Use - Scholia](https://user-images.githubusercontent.com/465923/139736805-c23f2110-83b2-4833-b1bc-4545401eade1.png)

The point of this ticket, then, is that the items listed in the "Use" column are currently linked just via their QID, e.g. the "Wikidata" entry in the table links to https://scholia.toolforge.org/Q2013 , which then typically redirects to [https://scholia.toolforge.org/**topic**/Q2013](https://scholia.toolforge.org/topic/Q2013) when the intent of the table is to link the "Use" column entries to [https://scholia.toolforge.org/**use**/Q2013](https://scholia.toolforge.org/use/Q2013).

Similarly, the entries in the "Described by example" column should probably point to the **work** aspect, e.g. the " Wikidata: A Free Collaborative Knowledgebase" entry to [https://scholia.toolforge.org/**work**/Q18507561](https://scholia.toolforge.org/work/Q18507561), which they currently do in most cases (via aspect guesser), but we could make it more explicit.
