### ISSUE TITLE
Convert topic aspects into external SPARQL query format

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1283]
as per https://github.com/fnielsen/scholia/pull/1267

- [x] topic (Egon): https://github.com/fnielsen/scholia/pull/1424
- [x] topics
- [x] disease
- [x] taxon (Egon)
- [x] gene
- [x] protein
- [x] pathway (Egon)
- [x] lexeme
- [x] use (Egon)

This excludes chem* aspects, which are handled in https://github.com/fnielsen/scholia/issues/1270 .

**Comment by egonw** [comment]
I'll take `taxon` because of https://github.com/fnielsen/scholia/issues/1300

**Comment by Daniel-Mietchen** [comment]
All of these are functional now.
