### ISSUE TITLE
Check that all SPARQL queries have been converted to externalized query format

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1284]
The goal here is to make sure that all SPARQL queries that were originally contained in .html pages have been moved to .sparql files and those .sparql files are called appropriately, as per https://github.com/fnielsen/scholia/pull/1267 .

**Comment by Daniel-Mietchen** [comment]
Also check for queries that are commented out, as per https://github.com/fnielsen/scholia/issues/1170 .

**Comment by Daniel-Mietchen** [comment]
Another thing to check here is that all queries have a proper HTML section ID, as per https://github.com/fnielsen/scholia/issues/1093 .

**Comment by carlinmack** [comment]
With the above merged PRs, @curibe can this be closed?

**Comment by fnielsen** [comment]
I supose. Do we have a "grep" that can check?

**Comment by carlinmack** [comment]
Not sure if this is thorough but:

```sh
/scholia/scholia/app/templates$ grep SELECT *.html
base.html:    SELECT DISTINCT ?aspect
base.html:    SELECT DISTINCT ?aspectsubpage
```

**Comment by carlinmack** [comment]
In the sidebar, click "Unpin this issue" 👍

**Comment by curibe** [comment]
> Not sure if this is thorough but:
> 
> ```shell
> /scholia/scholia/app/templates$ grep SELECT *.html
> base.html:    SELECT DISTINCT ?aspect
> base.html:    SELECT DISTINCT ?aspectsubpage
> ```

@carlinmack These queries was handled in this [PR](https://github.com/WDscholia/scholia/pull/1538) because it has JS code, and It is only in the base.html file
