### ISSUE TITLE
If an arxiv does not exist redirect to quickstatement construction

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#129]
If an arxiv does not exist redirect to quickstatement construction

**Comment by fnielsen** [comment]
Subissue of #130

**Comment by egonw** [comment]
Now that I figured out how to do a search-specific 404 page (see https://github.com/fnielsen/scholia/issues/787), we could use `citation.js` to create QuickStatements.

**Comment by fnielsen** [comment]
This works: 
http://127.0.0.1:8100/arxiv-to-quickstatements?arxiv=https%3A%2F%2Farxiv.org%2Fpdf%2F2107.02865.pdf
(arXiv is queried and QuickStatements are generated)
But this does not work:
http://127.0.0.1:8100/search?q=https%3A%2F%2Farxiv.org%2Fpdf%2F2107.02865.pdf
Instead we are just left with a "Not found".

**Comment by fnielsen** [comment]
This is related to a recent PR: https://github.com/WDscholia/scholia/pull/1490

**Comment by fnielsen** [comment]
BTW: It does work if the arXiv ID is present in Wikidata, e.g.,  https://arxiv.org/pdf/1710.04099 can be copy-pasted into the search field.
