### ISSUE TITLE
curation pages should use dash instead of underscore

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1339]

**Comment by Daniel-Mietchen** [comment]
That seems easy to do. Any specific reason for that?

**Comment by fnielsen** [comment]
There is a regular expression that formats the link to GitHub based on underscore.

**Comment by Daniel-Mietchen** [comment]
This seems to be a subset of #1332 .

**Comment by carlinmack** [comment]
I'm assigned but I think @DanielFLopez is handling this in #1487

**Comment by curibe** [comment]
@carlinmack #1487 solve partially the issue #1284. For the moment, the PR solve the externalization of sparql queries related with tables. The name of html files mentioned there was not  changed, only an internal variable. I had thought to change it in other PR

**Comment by DanielFLopez** [comment]
Are we talking about HTML files? Can you give me an example of where you are using underscore instead of a dash?

**Comment by carlinmack** [comment]
oh sorry! I got you two confused with the similar avatars. And doing a separate PR sounds good. Sorry for the confusion

**Comment by fnielsen** [comment]
author-curation.html instead of author_curation.html author-curation_panel-with-something.sparql instead of author_curation_panel-with-something.sparql.

**Comment by carlinmack** [comment]
Still outstanding:

- [ ] [author_curation.html](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/author_curation.html)
- [ ] [award_curation.html](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/award_curation.html)
- [ ] [organization_curation.html](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/organization_curation.html)
- [ ] [topic_curation.html](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/topic_curation.html)
- [ ] [venue_curation.html](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/venue_curation.html)
