### ISSUE TITLE
Scholia is down

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1357]
Has been down for about 20 min or so (not sure precisely), as per http://web.archive.org/web/20210305221750if_/https://downforeveryoneorjustme.com/scholia.toolforge.org?proto=https .

**Comment by Daniel-Mietchen** [comment]
And just as I am posting this, it is back ...

**Comment by egonw** [comment]
@Daniel-Mietchen, what should the action be here?

**Comment by fnielsen** [comment]
Could it be a restart: `webservice --backend=kubernetes -m 1G python3.7 restart`. After managing PR yesterday I did restart according to https://github.com/fnielsen/scholia/wiki. I am unsure about the timing "2021-03-05 11:16:10" is one log entry for the restart.

Restart usually seems to take less than 1 minute. I am not sure whether we can avoid that without getting into a complicated setup. I usually follow the log and see that it comes up with "reasonable" time. Yesterday, there did not seem to be any considerable long restart.

Another explanation could be other Toolforge-related issues. I have experienced issues with another Toolforge application, - possibly one of Werkmeister's.

Next time we might want to record hour:minute:second so we have timing for log examination.

**Comment by fnielsen** [comment]
I am getting "502 Bad Gateway" in Ordia now, - for just a single request

**Comment by fnielsen** [comment]
Possible issue on Phabricator: https://phabricator.wikimedia.org/T267966

**Comment by Daniel-Mietchen** [comment]
The issue has not reoccurred for some time, so closing this for now.
