### ISSUE TITLE
In "Supports the following statement(s)" panel on work aspect, add optional units

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1372]
Example:
https://scholia.toolforge.org/work/Q105645500
<img width="1131" alt="Screen Shot 2021-03-17 at 12 07 17" src="https://user-images.githubusercontent.com/465923/111499594-7c0b9c80-8719-11eb-981b-dfec4199ea33.png">

**Comment by fnielsen** [comment]
And when it is not a URI it shouldn't link

**Comment by Daniel-Mietchen** [comment]
Duplicate of #500.
