### ISSUE TITLE
Scraper for CEUR Workshop Proceedings

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1438]
CEUR Workshop Proceedings CEUR-WS at http://ceur-ws.org/ is open access non-doi articles from computer science workshops.

**Comment by WolfgangFahl** [comment]
@fnielsen we do the CEUR-WS / Wikidata synchronization regularly now and e.g. today we started a task for the current Knowledge Graph Lab WS2022 https://github.com/tholzheim/kgl-exercises/wiki/KG-Lab-WS-2022-23-Task-Scientific-Event-Series-Completion-and-Announcement-Crawler - shall we create specific further scholia issues according to our [Definition of Done Milestone for CEUR-WS Wikidata integration](https://github.com/WolfgangFahl/pyCEURmake/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Definition+of+Done+for+wikidata+migration%22)

**Comment by fnielsen** [comment]
@WolfgangFahl I am not sure what you mean. I was not planning on added CEUR proceedings regularly. If your system does that, that would be fine. I will probably just use it for entry of papers when I have interest in them, e.g., some of the Wikidata Workshop 2021 paper was apparently not entered.

**Comment by tholzheim** [comment]
@fnielsen The integration of all papers and their metadata to wikidata is planned for the upcoming weeks. At the time all proceedings and their events are already synchronized and linked to dblp if possible.
see [ceur-ws proceedings in wikidata](https://query.wikidata.org/#%23%0A%20%20%20%20%23%20get%20CEUR-WS%20Proceedings%20records%20by%20Volume%20with%20linked%20Event%20and%20EventSeries%0A%20%20%20%20%23%0A%20%20%20%20%23%20WF%202022-08-13%0A%20%20%20%20%23%0A%20%20%20%20%23%20the%20Volume%20number%20P478%20is%20sometimes%20available%20with%20the%20proceedings%20item%20and%20sometimes%20as%20a%20qualifier%0A%20%20%20%20%23%20of%0A%20%20%20%20%23%0A%20%20%20%20PREFIX%20pq%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fqualifier%2F%3E%0A%20%20%20%20PREFIX%20p%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2F%3E%0A%20%20%20%20PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%20%20%20%20PREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A%20%20%20%20PREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0A%20%20%20%20PREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0A%20%20%20%20PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20%20%20SELECT%20%3Fitem%20%3FitemLabel%20%3FitemDescription%0A%20%20%20%20%20%20%3FsVolume%0A%20%20%20%20%20%20%3Fshort_name%0A%20%20%20%20%20%20%23%20identifiers%0A%20%20%20%20%20%20%3FdblpProceedingsId%0A%20%20%20%20%20%20%3FppnId%0A%20%20%20%20%20%20%23%20event%0A%20%20%20%20%20%20%3Fevent%0A%20%20%20%20%20%20%3FeventLabel%0A%20%20%20%20%20%20%3FdblpEventId%0A%20%20%20%20%20%20%23%20eventSeries%0A%20%20%20%20%20%20%23%3FpartOfTheEventSeriesStmt%0A%20%20%20%20%20%20%3FeventSeries%0A%20%20%20%20%20%20%3FeventSeriesLabel%0A%20%20%20%20%20%20%3FeventSeriesOrdinal%0A%20%20%20%20%20%20%23%20details%0A%20%20%20%20%20%20%3Ftitle%20%3Flanguage_of_work_or_nameLabel%0A%20%20%20%20%20%20%3FURN_NBN%20%3FURN_NBNUrl%0A%20%20%20%20%20%20%3Fpublication_date%0A%20%20%20%20%20%20%3FfullWorkUrl%0A%20%20%20%20%20%20%3Fdescribed_at_URL%0A%20%20%20%20%20%20%3FhomePage%0A%20%20%20%20%20%20%3Flocation%0A%20%20%20%20%20%20%3Fcountry%0A%20%20%20%20%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel.%0A%20%20%20%20%20%20FILTER%28LANG%28%3FitemLabel%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20schema%3Adescription%20%3FitemDescription.%0A%20%20%20%20%20%20%20%20FILTER%28LANG%28%3FitemDescription%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%20%20%23%20Instance%20of%20Proceedings%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP31%20wd%3AQ1143604.%0A%20%20%20%20%20%20%23%20Part%20of%20the%20series%0A%20%20%20%20%20%20%3Fitem%20p%3AP179%20%3FpartOfTheSeries.%0A%20%20%20%20%20%20%23%20CEUR%20Workshop%20proceedings%0A%20%20%20%20%20%20%3FpartOfTheSeries%20ps%3AP179%20wd%3AQ27230297.%0A%20%20%20%20%0A%20%20%20%20%20%20%23%20Volume%20directly%20with%20the%20proceeedings%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP478%20%3FVolume.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Volumes%20via%20a%20a%20qualifier%20of%20the%20part%20of%20the%20series%20relation%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3FpartOfTheSeries%20pq%3AP478%20%3FsVolume.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Acronym%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP1813%20%3Fshort_name.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20External%20Identifiers%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%09%23%20DBLP%20event%20ID%0A%20%20%20%20%20%20%09%23%20identifier%20for%20scientific%20events%20in%20the%20DBLP%20computer%20science%20bibliography%0A%20%20%20%20%20%20%09%3Fitem%20wdt%3AP8978%20%3FdblpProceedingsId.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%23%20K10plus%20PPN%20ID%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP6721%20%3FppnId.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20event%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP4745%20%3Fevent.%0A%20%20%20%20%20%20%20%20%3Fevent%20rdfs%3Alabel%20%3FeventLabel.%0A%20%20%20%20%20%20%20%20FILTER%28LANG%28%3FeventLabel%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3Fevent%20p%3AP179%20%3FpartOfTheEventSeriesStmt.%0A%20%20%20%20%20%20%20%20%20%20%3FpartOfTheEventSeriesStmt%20ps%3AP179%20%3FeventSeries.%0A%20%20%20%20%20%20%20%20%20%20%3FpartOfTheEventSeriesStmt%20pq%3AP1545%20%3FeventSeriesOrdinal.%0A%20%20%20%20%20%20%20%20%20%20%23%3Fevent%20wdt%3AP179%20%3FeventSeries.%0A%20%20%20%20%20%20%20%20%20%20%3FeventSeries%20rdfs%3Alabel%20%3FeventSeriesLabel.%0A%20%20%20%20%20%20%20%20%20%20FILTER%28LANG%28%3FeventSeriesLabel%29%20%3D%20%22en%22%29.%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%0A%20%20%20%20%20%20%20%20%20%20%3Fevent%20wdt%3AP10692%20%3FdblpEventId.%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%3Fevent%20wdt%3AP276%20%3Flocation%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%3Fevent%20wdt%3AP17%20%3Fcountry%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Title%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP1476%20%3Ftitle.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Language%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP407%20%3Flanguage_of_work_or_name.%0A%20%20%20%20%20%20%20%20%3Flanguage_of_work_or_name%20rdfs%3Alabel%20%3Flanguage_of_work_or_nameLabel.%0A%20%20%20%20%20%20%20%20FILTER%28LANG%28%3Flanguage_of_work_or_nameLabel%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20The%20URN%20shouldn%27t%20be%20optional%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP4109%20%3FURN_NBN.%0A%20%20%20%20%20%20%20%20wd%3AP4109%20wdt%3AP1630%20%3FURN_NBNFormatterUrl.%0A%20%20%20%20%20%20%20%20BIND%28IRI%28REPLACE%28%3FURN_NBN%2C%20%27%5E%28.%2B%29%24%27%2C%20%3FURN_NBNFormatterUrl%29%29%20AS%20%3FURN_NBNUrl%29.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20publication%20date%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP577%20%3Fpublication_date.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20full%20work%20available%20at%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP953%20%3FfullWorkUrl%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20described%20at%20url%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP973%20%3Fdescribed_at_URL.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20homepage%20-%3E%20replace%20with%20full%20work%20available%20at%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP856%20%3FhomePage%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20ORDER%20BY%20xsd%3Ainteger%28%3FsVolume%29)

**Comment by fnielsen** [comment]
> @fnielsen The integration of all papers and their metadata to wikidata is planned for the upcoming weeks. At the time all proceedings and their events are already synchronized and linked to dblp if possible. see [ceur-ws proceedings in wikidata](https://query.wikidata.org/#%23%0A%20%20%20%20%23%20get%20CEUR-WS%20Proceedings%20records%20by%20Volume%20with%20linked%20Event%20and%20EventSeries%0A%20%20%20%20%23%0A%20%20%20%20%23%20WF%202022-08-13%0A%20%20%20%20%23%0A%20%20%20%20%23%20the%20Volume%20number%20P478%20is%20sometimes%20available%20with%20the%20proceedings%20item%20and%20sometimes%20as%20a%20qualifier%0A%20%20%20%20%23%20of%0A%20%20%20%20%23%0A%20%20%20%20PREFIX%20pq%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fqualifier%2F%3E%0A%20%20%20%20PREFIX%20p%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2F%3E%0A%20%20%20%20PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%20%20%20%20PREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A%20%20%20%20PREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0A%20%20%20%20PREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0A%20%20%20%20PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20%20%20SELECT%20%3Fitem%20%3FitemLabel%20%3FitemDescription%0A%20%20%20%20%20%20%3FsVolume%0A%20%20%20%20%20%20%3Fshort_name%0A%20%20%20%20%20%20%23%20identifiers%0A%20%20%20%20%20%20%3FdblpProceedingsId%0A%20%20%20%20%20%20%3FppnId%0A%20%20%20%20%20%20%23%20event%0A%20%20%20%20%20%20%3Fevent%0A%20%20%20%20%20%20%3FeventLabel%0A%20%20%20%20%20%20%3FdblpEventId%0A%20%20%20%20%20%20%23%20eventSeries%0A%20%20%20%20%20%20%23%3FpartOfTheEventSeriesStmt%0A%20%20%20%20%20%20%3FeventSeries%0A%20%20%20%20%20%20%3FeventSeriesLabel%0A%20%20%20%20%20%20%3FeventSeriesOrdinal%0A%20%20%20%20%20%20%23%20details%0A%20%20%20%20%20%20%3Ftitle%20%3Flanguage_of_work_or_nameLabel%0A%20%20%20%20%20%20%3FURN_NBN%20%3FURN_NBNUrl%0A%20%20%20%20%20%20%3Fpublication_date%0A%20%20%20%20%20%20%3FfullWorkUrl%0A%20%20%20%20%20%20%3Fdescribed_at_URL%0A%20%20%20%20%20%20%3FhomePage%0A%20%20%20%20%20%20%3Flocation%0A%20%20%20%20%20%20%3Fcountry%0A%20%20%20%20%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel.%0A%20%20%20%20%20%20FILTER%28LANG%28%3FitemLabel%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20schema%3Adescription%20%3FitemDescription.%0A%20%20%20%20%20%20%20%20FILTER%28LANG%28%3FitemDescription%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%20%20%23%20Instance%20of%20Proceedings%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP31%20wd%3AQ1143604.%0A%20%20%20%20%20%20%23%20Part%20of%20the%20series%0A%20%20%20%20%20%20%3Fitem%20p%3AP179%20%3FpartOfTheSeries.%0A%20%20%20%20%20%20%23%20CEUR%20Workshop%20proceedings%0A%20%20%20%20%20%20%3FpartOfTheSeries%20ps%3AP179%20wd%3AQ27230297.%0A%20%20%20%20%0A%20%20%20%20%20%20%23%20Volume%20directly%20with%20the%20proceeedings%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP478%20%3FVolume.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Volumes%20via%20a%20a%20qualifier%20of%20the%20part%20of%20the%20series%20relation%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3FpartOfTheSeries%20pq%3AP478%20%3FsVolume.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Acronym%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP1813%20%3Fshort_name.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20External%20Identifiers%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%09%23%20DBLP%20event%20ID%0A%20%20%20%20%20%20%09%23%20identifier%20for%20scientific%20events%20in%20the%20DBLP%20computer%20science%20bibliography%0A%20%20%20%20%20%20%09%3Fitem%20wdt%3AP8978%20%3FdblpProceedingsId.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%23%20K10plus%20PPN%20ID%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP6721%20%3FppnId.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20event%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP4745%20%3Fevent.%0A%20%20%20%20%20%20%20%20%3Fevent%20rdfs%3Alabel%20%3FeventLabel.%0A%20%20%20%20%20%20%20%20FILTER%28LANG%28%3FeventLabel%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3Fevent%20p%3AP179%20%3FpartOfTheEventSeriesStmt.%0A%20%20%20%20%20%20%20%20%20%20%3FpartOfTheEventSeriesStmt%20ps%3AP179%20%3FeventSeries.%0A%20%20%20%20%20%20%20%20%20%20%3FpartOfTheEventSeriesStmt%20pq%3AP1545%20%3FeventSeriesOrdinal.%0A%20%20%20%20%20%20%20%20%20%20%23%3Fevent%20wdt%3AP179%20%3FeventSeries.%0A%20%20%20%20%20%20%20%20%20%20%3FeventSeries%20rdfs%3Alabel%20%3FeventSeriesLabel.%0A%20%20%20%20%20%20%20%20%20%20FILTER%28LANG%28%3FeventSeriesLabel%29%20%3D%20%22en%22%29.%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%0A%20%20%20%20%20%20%20%20%20%20%3Fevent%20wdt%3AP10692%20%3FdblpEventId.%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%3Fevent%20wdt%3AP276%20%3Flocation%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%3Fevent%20wdt%3AP17%20%3Fcountry%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Title%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP1476%20%3Ftitle.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20Language%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP407%20%3Flanguage_of_work_or_name.%0A%20%20%20%20%20%20%20%20%3Flanguage_of_work_or_name%20rdfs%3Alabel%20%3Flanguage_of_work_or_nameLabel.%0A%20%20%20%20%20%20%20%20FILTER%28LANG%28%3Flanguage_of_work_or_nameLabel%29%20%3D%20%22en%22%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20The%20URN%20shouldn%27t%20be%20optional%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP4109%20%3FURN_NBN.%0A%20%20%20%20%20%20%20%20wd%3AP4109%20wdt%3AP1630%20%3FURN_NBNFormatterUrl.%0A%20%20%20%20%20%20%20%20BIND%28IRI%28REPLACE%28%3FURN_NBN%2C%20%27%5E%28.%2B%29%24%27%2C%20%3FURN_NBNFormatterUrl%29%29%20AS%20%3FURN_NBNUrl%29.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20publication%20date%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP577%20%3Fpublication_date.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20full%20work%20available%20at%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP953%20%3FfullWorkUrl%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20described%20at%20url%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP973%20%3Fdescribed_at_URL.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20homepage%20-%3E%20replace%20with%20full%20work%20available%20at%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP856%20%3FhomePage%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20ORDER%20BY%20xsd%3Ainteger%28%3FsVolume%29)

Fine!
