### ISSUE TITLE
Scholia Docker image

### ISSUE THREAD

**Issue by thewillyhuman** [WDscholia/scholia#1452]
Hello,

I was wondering if Scholia already has an official docker/container image. I have created one with the following configuration.

```Dockerfile
FROM python:latest

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8100

CMD [ "python3", "runserver.py"]
```

And modifying the `runserver.py` file as follows:
```python
app.run(debug=True, port=8100, host='0.0.0.0')
```
This image is available at docker hub as [wesogroup/scholia](https://hub.docker.com/repository/docker/wesogroup/scholia).

But, I don't know how I could tell Scholia in the runserver.py to start listening to all hosts without adding the `host=0.0.0.0` parameter in the `app.run(...)` method. Any idea?

I have been looking and I think the following issues might be related (https://github.com/fnielsen/scholia/issues/966, https://github.com/fnielsen/scholia/issues/1058). Are there any more updates on them other than what can be seen on GitHub?

Thank you very much.

**Comment by thewillyhuman** [comment]
Looking to the PRs of the projects just found that PR #1037 states that the host parameter should be configurable https://github.com/fnielsen/scholia/pull/1037#discussion_r383374032. Is this already implemented?

**Comment by egonw** [comment]
ping @ammar257ammar

**Comment by fnielsen** [comment]
At one point, I think we had a PR, but I might have been too slow to accept it. I have used docker but insufficiently to do a quick review of the dockerfile, so I might need some explanation/help.

**Comment by thewillyhuman** [comment]
Hi @fnielsen,

If you want, I could try to help you without any problem. In the modifications, we made in [weso/scholia:add-dockerfile](https://github.com/weso/scholia/tree/weso/add-dockerfile) [(diff here)](https://github.com/WDscholia/scholia/compare/master...weso:weso/add-dockerfile?expand=1) I had to make a modification in the `runserver.py` file to be able to activate incoming connections from any IP. I think you guys solve this by using a proxy. Also, I thought I read in a PR of the original repository that the desired behavior is that it only listens on the local IP and the rest are configurations or something like that.

However, I would like to know more about how you deploy it in "production". That way maybe I can get a better idea of what the needs are.

**Comment by Daniel-Mietchen** [comment]
Re how to deploy Scholia in production, see https://github.com/WDscholia/scholia/wiki#updates-for-wmflabs and https://wikitech.wikimedia.org/wiki/Portal:Toolforge .

The ```host='0.0.0.0'``` modification would also address another issue, #1327 .

**Comment by Daniel-Mietchen** [comment]
@thewillyhuman I just made a PR for that ```host='0.0.0.0'``` bit: https://github.com/WDscholia/scholia/pull/1482 .

**Comment by thewillyhuman** [comment]
Oh, thanks. Just to be sure, here in this comment (https://github.com/WDscholia/scholia/pull/1037#discussion_r383374032) you discussed this as a possible security risk and the conclusion was _"Default on localhost and then perhaps configurable"_. If this is a real issue for you I don't think it is critical right now, at least for our goal. Anyway, a million thanks for the PR.
