### ISSUE TITLE
Authors should be distinct in "recently published works" panel in venue aspect

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1459]
Example where it fails: https://scholia.toolforge.org/venue/Q100718036 In this case it is because there are two publication dates.

**Comment by Daniel-Mietchen** [comment]
Screenshot of the example, with the problematic part highlighted:
<img width="1152" alt="Screen Shot 2021-06-22 at 19 28 03" src="https://user-images.githubusercontent.com/465923/123012278-f9395400-d38f-11eb-9b6d-d97699cf67f1.png">
