### ISSUE TITLE
Add summary of reviews to author aspect

### ISSUE THREAD

**Issue by cthoyt** [WDscholia/scholia#1468]
Following discussion on https://twitter.com/cthoyt/status/1408584166287966210, I was able to modify the [author-venue-statistics SPARQL query](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/author_venue-statistics.sparql) to use [P4032 (reviewed by)](https://www.wikidata.org/wiki/Property:P4032) instead of [P50 (author)](https://www.wikidata.org/wiki/Property:P50). Using Finn as an example (see https://w.wiki/3ZAe), I was able to build a table with counts of reviews for various venues:

<img width="1337" alt="Screen Shot 2021-06-28 at 08 18 15" src="https://user-images.githubusercontent.com/5069736/123635229-70844300-d7e9-11eb-8793-14610f9e13cd.png">

This is keeping in mind that there aren't lots of open resources for sucking this kind of data in. I'd also like to make a query for the specific articles themselves to debug and will edit this description to include an example once I've made one I'm happy with

**Comment by fnielsen** [comment]
What about the "program committe" property? Should that be added?

**Comment by cthoyt** [comment]
Context: [P5804 (has program committee member)](https://www.wikidata.org/wiki/Property:P5804) does seem to imply that all program committee members are responsible for reviewing work.

To add this, this query would need a union since the query would be something like venue -> has program committee member -> person, venue -> has proceedings -> proceedings, work -> has venue -> proceedings

**Comment by fnielsen** [comment]
This is now running: https://scholia.toolforge.org/author/Q20980928
