### ISSUE TITLE
upgraded bar plot where you can (un)select a category

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#1472]
It would be nice to be able to select and unselect categories in plots like this one:

![image](https://user-images.githubusercontent.com/26721/123921679-8fb8d700-d987-11eb-8780-cdfb14acdb17.png)

**Comment by carlinmack** [comment]
You can click on the label in the legend to show or hide a category

![image](https://user-images.githubusercontent.com/6676843/128012472-a90bc435-613d-4ea4-82ef-3d111cdd0f30.png)
![image](https://user-images.githubusercontent.com/6676843/128012475-f4f0d21b-361b-46bb-b440-e7945ee6d381.png)
