### ISSUE TITLE
Consider pinning issues 

### ISSUE THREAD

**Issue by carlinmack** [WDscholia/scholia#1494]
On GitHub, you can pin an issue via its sidebar and it will appear on the issues tab like this https://github.com/hfg-gmuend/openmoji/issues. This is a good place to highlight issues of general interest (perhaps a thread for user feedback) or long term goals (so that potential contributors can see what's important. At OpenMoji we had [this issue](https://github.com/hfg-gmuend/openmoji/issues/124) pinned so new contributors could quickly find an emoji to work on).

I don't have suggestions for specific issues, but hopefully some issues spring to mind.

**Comment by Daniel-Mietchen** [comment]
We have some pinned issues now. Thanks for the suggestion.
