### ISSUE TITLE
Paragraph breaks are removed, with no space substituted.

### ISSUE THREAD

**Issue by pigsonthewing** [WDscholia/scholia#1501]
On https://scholia.toolforge.org/topic/Q936 I see text from the English Wikipedia, including "satellite navigation devices.Created by Steve Coast ".

On Scholia, there is no space between "devices" and "Created". 

On the Wikipedia article there is a paragraph break between "devices" and "Created".

**Comment by carlinmack** [comment]
Unfortunately this seems to be a long-standing bug with the TextExtract extension which our API relies on https://phabricator.wikimedia.org/T201946

**Comment by Daniel-Mietchen** [comment]
We could in principle look into patching TextExtract [upstream](https://phabricator.wikimedia.org/T201946#4569825).

**Comment by Daniel-Mietchen** [comment]
An alternative option discussed in that Phabricator ticket would be to switch to the summary REST API:
https://en.wikipedia.org/api/rest_v1/page/summary/OpenStreetMap
<img width="903" alt="Screen Shot 2021-07-12 at 14 39 48" src="https://user-images.githubusercontent.com/465923/125339196-13c37500-e31f-11eb-801c-22b8da4e4b98.png">

**Comment by carlinmack** [comment]
I using the REST API would be a good change as it also gets rid the pronunciation which can be quite distracting:

![image](https://user-images.githubusercontent.com/6676843/126803406-8495fd1d-b8bf-441e-994f-5b4fc889927a.png)
