### ISSUE TITLE
DOI to quickstatement does not forward full quickstatements

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1508]
Example: 
- Go to https://scholia.toolforge.org/doi/10.1136/bmj.n1656
- Metadata is fetch ok
- Press "Submit to QuickStatements"
- Only the first QuickStatement line is shown (instance of).

I am not sure what happened. Have we changed anything in the code? Has quickstatement? Why do citation-js has a newline after CREATE? Is that a problem? The URL is https://quickstatements.toolforge.org/#/v1=%7CCREATE%7C%7C%7C%7C%7CLAST%7CP31%7CQ13442814%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CLen%7C%22The%20covid-19%20lab%20leak%20hypothesis:%20did%20the%20media%20fall%20victim%20to%20a%20misinformation%20campaign?%22%7C%7C%7CLAST%7CP304%7C%22n1656%22%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CP356%7C%2210.1136%2FBMJ.N1656%22%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CP407%7CQ1860%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CP577%7C+2021-07-08T00:00:00Z%2F11%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CP1433%7CQ546003%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CP1476%7Cen:%22The%20covid-19%20lab%20leak%20hypothesis:%20did%20the%20media%20fall%20victim%20to%20a%20misinformation%20campaign?%22%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7CLAST%7CP2093%7C%22Paul%20D%20Thacker%22%7CP1545%7C%221%22%7CS248%7CQ5188229%7CS813%7C+2021-07-14T00:00:00Z%2F11%7C%7C%7C%7C

**Comment by fnielsen** [comment]
Once the item is created it can be merged with Q107524799

**Comment by fnielsen** [comment]
The excessive "%7C"s do not seem to be the problem.

**Comment by fnielsen** [comment]
Another DOI is not a problem: https://scholia.toolforge.org/doi/10.1038/d41586-021-01893-0 for instance work ok

**Comment by fnielsen** [comment]
@egonw @larsgw I wonder if you have any clue about this issue. I have been trying to mangle the URL but to no avail.

**Comment by fnielsen** [comment]
Maybe it is the question mark in the end of the title.

**Comment by fnielsen** [comment]
If the question make "?" is changed to "%3F" it works.

**Comment by egonw** [comment]
Thx for the ping! I'll pick it up.

**Comment by fnielsen** [comment]
I think encodeURIComponent should be used instead of encodeURI at https://github.com/WDscholia/scholia/blob/2b5d2b1e2135f688ece0d173ea2d71d1248d0b15/scholia/app/templates/404_doi.html#L13

**Comment by larsgw** [comment]
Yeah I think someone encountered it already and put this (partial) fix in:
https://github.com/WDscholia/scholia/blob/2b5d2b1e2135f688ece0d173ea2d71d1248d0b15/scholia/app/templates/404_doi.html#L16
