### ISSUE TITLE
Rename author-index-curation.html to author-curation

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1523]
@egonw I am not sure why this file got called author-index-curation.html and not author-curation. A file called author-index-curation.html could be a curation page for authors where no q item is given, but in this case the q-item is given.

There is a dependency on PR #1513.

**Comment by egonw** [comment]
Seems I made a mistake there: https://github.com/WDscholia/scholia/commit/7fbe0e23b191cb925cff76d102400bf2df9b9c0d

**Comment by egonw** [comment]
A `git revert 7fbe0e23b191cb925cff76d102400bf2df9b9c0d` should do it.

**Comment by fnielsen** [comment]
Fixed with https://github.com/WDscholia/scholia/pull/1513/commits/853432a0b400f57af23eaafae0200837b4a868ed by @DanielFLopez
