### ISSUE TITLE
Python2 incompatible syntax in views.py

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1528]
scholia/app/views.py:2151:56: E999 SyntaxError: invalid syntax introduced in https://github.com/WDscholia/scholia/pull/1513/commits/114860dece24b54c5abe5d45bcdfd7386ec073b7

**Comment by egonw** [comment]
@fnielsen, I think this because Python 2.7 and 3.5 are no longer available. The syntax is fine, and the error is a symptom. I made a PR for updating the build environment here: https://github.com/WDscholia/scholia/pull/1531

**Comment by fnielsen** [comment]
> I think this because Python 2.7 and 3.5 are no longer available.

No, this is because of the new `f'{aspect}` syntax.
