### ISSUE TITLE
Why is the PR not warning about certain issues?

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1529]
For instance, https://github.com/WDscholia/scholia/issues/1528 problem was not indicated

**Comment by egonw** [comment]
It depends where the branch is located that is mentioned/used(?) in the pull request. Some weeks (months?) ago I filed the same issue (will look it up). For example, when I push the branch to my personal fork, then it doesn't do the checking. Could this explain your observation too?

**Comment by egonw** [comment]
For example, when I push a branch into my personal fork, you will find the test results here: https://github.com/egonw/scholia/actions

**Comment by carlinmack** [comment]
> Some weeks (months?) ago I filed the same issue 

#1442
