### ISSUE TITLE
An ORCiD id is used as a property on a Author Name String 

### ISSUE THREAD

**Issue by GerardMeijssen** [WDscholia/scholia#1533]
I love the ability of Scholia to find authors.. However, check out https://www.wikidata.org/wiki/Q107589286 and you will notice a name string where an author should / could exist.. but where you find the ORCiD id as a property
Thanks, GerardM

**Comment by carlinmack** [comment]
Perhaps also suggestion for https://github.com/arthurpsmith/author-disambiguator

**Comment by fnielsen** [comment]
It is not clear what the "issue" is. So I am going to close this issue. The setup of articles with citation-js and QuickStatements can use the ORCID iD from CrossRef.
