### ISSUE TITLE
<aspect>_empty should be <aspect>-index

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1554]
cito_empty should be cito-index

**Comment by carlinmack** [comment]
There are actually many outstanding `empty` files

![image](https://user-images.githubusercontent.com/6676843/127470868-80782d45-b8dd-4d4a-b28b-224ce87db24d.png)

- [ ] award_empty.html
- [ ] catalogue_empty.html
- [ ] chemical_class_empty.html
- [ ] chemical_class_publications-per-year.sparql
- [ ] chemical_element_empty.html
- [ ] chemical_publications-per-year.sparql
- [ ] cito_empty_article-counts.sparql
- [ ] cito_empty_articles-by-year.sparql
- [ ] cito_empty_journal-counts.sparql
- [ ] cito_empty_statistics.sparql
- [ ] cito_empty.html
- [ ] complex_empty_statistics.sparql
- [ ] complex_empty.html
- [ ] country_empty.html
- [ ] disease_empty.html
- [ ] event_empty.html
- [ ] event_series_empty.html
- [ ] gene_empty.html
- [ ] lexeme_empty.html
- [ ] location_empty.html
- [ ] organization_empty.html
- [ ] pathway_empty.html
- [ ] project_empty.html
- [ ] protein_empty.html
- [ ] publisher_empty.html
- [ ] series_empty.html
- [ ] software_empty.html
- [ ] sponsor_empty.html
- [ ] taxon_empty.html
- [ ] topic_empty.html
- [ ] use_empty.html
- [ ] venue_empty.html
- [ ] work_empty.html

**Comment by carlinmack** [comment]
Also: "All HTML and sparql files should be called with a dash instead of an underscore" however 348/398 of templates still have underscores? (212/398 have dashes)
