### ISSUE TITLE
Add OpenTrials ID to statistics in clinical-trials aspect

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1564]
```sparql
  UNION
  {
    { SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P6220 [] . } }
    BIND("Links to OpenTrials" AS ?description)
  }
```

**Comment by DanielFLopez** [comment]
is this what you requested? @fnielsen 

![Screen Shot 2021-08-23 at 10 31 53 AM](https://user-images.githubusercontent.com/14321810/130475038-c9e19da7-329d-4111-b968-613e76571a3b.png)
