### ISSUE TITLE
minor error prevents creation of new item

### ISSUE THREAD

**Issue by GerardMeijssen** [WDscholia/scholia#1568]
This 10.1111/1365-2745.13499 paper includes many known authors.. also some new ones. It however fails in the Quickstatements because of an error. This error is imho minor.. can the code be improved so that the item for the paper will be included?

**Comment by egonw** [comment]
Ah, an example of a title with newlines that I ran into yesterday myself too. I just pushed a fix.

Workaround: copy/past the QS commands manually to QuickStatements, remove the newlines, and then import them

**Comment by egonw** [comment]
Believed to be the same issue as https://github.com/WDscholia/scholia/issues/1571

**Comment by GerardMeijssen** [comment]
Hoi,
De search geeft mij op dit moment "bad gateway".. mogelijk moet de service
opnieuw gestart worden.
Gerard

**Comment by egonw** [comment]
Not sure what you mean. https://scholia.toolforge.org/doi/10.1111/1365-2745.13499 works for me.
