### ISSUE TITLE
Allow to set language by URL parameter

### ISSUE THREAD

**Issue by waldenn** [WDscholia/scholia#1575]
Hi,

It seems there is currently no way to change the preferred language of the Scholia user interface and for the Scholia SPARQL queries (which currently only uses AUTO_LANGUAGE).

Allowing for a language-parameter like eg. "https://scholia.toolforge.org/topic/Q183?uselang=de" (as Wikidata also does) could be very useful I think.

**Comment by Daniel-Mietchen** [comment]
Thanks for the suggestion, @waldenn . We have #767 for this already, so closing this as a duplicate.

**Comment by fnielsen** [comment]
Yes, thanks @waldenn. We are working on this. Perhaps we will have something in the end of this month.
