### ISSUE TITLE
`sparqlToDataTable` is never called

### ISSUE THREAD

**Issue by carlinmack** [WDscholia/scholia#1578]
Searching the repository, `sparqlToDataTable` is only defined, never called

![image](https://user-images.githubusercontent.com/6676843/128696602-10054393-27a8-4811-97c2-94ccaf262026.png)

compare to `sparqlToDataTable2`

![image](https://user-images.githubusercontent.com/6676843/128696566-9cfced92-14a1-42af-92fa-f51d3fe5e121.png)

**Comment by fnielsen** [comment]
If I remember correctly `sparqlToDataTable2` was made in connection with a transition. If the old `sparqlToDataTable` is not called then `sparqlToDataTable2` should be called `sparqlToDataTable`.

**Comment by egonw** [comment]
nice, good indication the transition is complete :)
