### ISSUE TITLE
Add 'complex' aspect to menu

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1587]
Add 'complex' aspect to menu

**Comment by DanielFLopez** [comment]
do you want to add complex to the menus on the main page? In which of the menus should I add it?

<img width="1308" alt="Screen Shot 2021-08-23 at 9 41 37 AM" src="https://user-images.githubusercontent.com/14321810/130467189-9c72d4cd-e6f7-4d4d-bfed-56c3026f970f.png">

**Comment by Daniel-Mietchen** [comment]
I think it should go under the Topics header and be listed under "Chemical class".
