### ISSUE TITLE
In dependency graph on software profile, add licenses

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1595]
e.g. for
https://scholia.toolforge.org/software/Q45340488 ,
the query would look as follows:

```SPARQL
# tool: scholia
#description: Show software library, programming language and developer dependencies 
#defaultView:Graph
SELECT ?resource1 ?resource1Label ?image1 ?rgb ?resource2 ?resource2Label ?image2
WITH {
  SELECT
    ?resource1 (SAMPLE(?image1_) AS ?image1) ?rgb
    ?resource2 (SAMPLE(?image2_) AS ?image2)
    {
      {
        # root node with coloring
        BIND(wd:Q45340488 AS ?resource1)
        BIND("3080BB" AS ?rgb)
      }
      UNION
      {
        # dependencies, programming language, developer
        wd:Q45340488 ( wdt:P1547 | wdt:P277 | wdt:P178 | wdt:P275 )+ ?resource1 .
        OPTIONAL { ?resource1 wdt:P18 ?image1_ }
      }
      wd:Q45340488 ( wdt:P1547 | wdt:P277 | wdt:P178 | wdt:P275 )+ ?resource2 .
      OPTIONAL { ?resource2 wdt:P18 ?image2_ }
      ?resource1 ( wdt:P1547 | wdt:P277 | wdt:P178 | wdt:P275 ) ?resource2 .
    }
    GROUP BY ?resource1 ?resource2 ?rgb
} AS %result
{
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}

```

**Comment by fnielsen** [comment]
Interesting, but does the graph begins to be somewhat cluttered?

**Comment by Daniel-Mietchen** [comment]
I think cluttering is less of a concern here than for some of the other graphs. For one, the user can interact with the graph by zooming and dragging as appropriate. Two, the number of licenses used for software is not too large, so if there were a large number of dependencies in the results for a particular item, the licenses would assist with clustering.

Perhaps we could nonetheless consider two enhancements:
- adding a LIMIT or even two (i.e. one for a subgraph, e.g. as in the co-author network graphs)
- colouring the connections by item class

**Comment by carlinmack** [comment]
It would be great if the license could be encoded by colour (which would nicely show the infectiveness of GPL), however I don't think you can show legends with the current chart

**Comment by Daniel-Mietchen** [comment]
We could explain the colors verbally in the HTML, or we could hope that users will figure out that colors go by type.

**Comment by carlinmack** [comment]
But we would want it to be dynamic as there are many licenses :(

**Comment by fnielsen** [comment]
> But we would want it to be dynamic as there are many licenses :(

It is possible to force nodes to a specific color, so I do not see that as an issue. We color also color humans
