### ISSUE TITLE
Non-preprint marked as pre-print

### ISSUE THREAD

**Issue by carlinmack** [WDscholia/scholia#1597]
https://scholia.toolforge.org/work/Q102092244 is noted as a preprint, but is an erratum. Perhaps I messed up the SPARQL?

**Comment by fnielsen** [comment]
Yes, it seems I was a bit too fast accepting this. I thought we had a "preprint" property? But apparently no.

**Comment by carlinmack** [comment]
there is a preprint property (instance of preprint), but the thing to get the published version must be too general

**Comment by carlinmack** [comment]
To be honest, I'm not good enough with SPARQL to specify the statement must be a `Q580922` (preprint)

```
?work p:P31 ?statement .
?statement pq:P642 ?pub .
```

I think I might need a `psv:`.

It would be good if the person that closes this could make a PR that adds an "Erratum of:" using the above as an example

**Comment by egonw** [comment]
> It would be good if the person that closes this could make an additional PR to add an "Erratum of:" row

Yes, will fix this too. Also applies to retractions where it's also missing:

![image](https://user-images.githubusercontent.com/26721/209994686-23efebb1-37ee-464f-9863-0db5c7485e1d.png)
