### ISSUE TITLE
Why is CiTO a subpage and not included on the item page?

### ISSUE THREAD

**Issue by carlinmack** [WDscholia/scholia#1610]
Currently we have https://scholia.toolforge.org/work/Q21090124/cito and https://scholia.toolforge.org/venue/Q6294930/cito, but could these panels not be placed on the main item page? 

Subaspects and curation pages make sense to me as subpages as they both require a different context, however I don't see why it's the case with CiTO annotation panels.

Is it because these panels are only relevant for very few items, and therefore would be blank on most pages?  If so I'll investigate a way to show/hide panels based upon the results of a SPARQL query? (#741) 

This is part of #1322

**Comment by carlinmack** [comment]
PS a discussion label would be nice, maybe I've missed an equivalent

**Comment by egonw** [comment]
@carlinmack, at this moment, there is only a minimal amount of CiTO annotation in Wikidata (see https://scholia.toolforge.org/cito/) and we do not have a mechanism yet to hide/collapse a panel fully when there is no data to show.
