### ISSUE TITLE
Searching for a DOI may bring wrong feedback 

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1654]
Searching for http://dx.doi.org/10.1093/nar/gkw1099 https://scholia.toolforge.org/search?q=http://dx.doi.org/10.1093/nar/gkw1099 brings a error message `No results for ""`
Possibly temporary due to timeout

**Comment by carlinmack** [comment]
Clicking the second link brings me to the UniProt page, weird

**Comment by Daniel-Mietchen** [comment]
Actually, the redirect to UniProt: the universal protein knowledgebase (Q37556842) is expected behavior. Perhaps this was just a temporary glitch.

**Comment by Daniel-Mietchen** [comment]
This looks fixed to me. Perhaps we can close it?

**Comment by fnielsen** [comment]
hmmm.... Could be a temporary timeout problem.
