### ISSUE TITLE
DOI to QuickStatements workflow seems broken

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1659]
Here is what I am currently getting for 
https://scholia.toolforge.org/doi/10.1080/09589236.2015.1087309 :

![Screenshot 2021-09-02 at 21-29-32 Scholia](https://user-images.githubusercontent.com/465923/131937048-9a93eb6f-67b8-413d-8a06-cf31b955bb62.png)

This is while I am logged in to QuickStatements as usual, so here is how it looks in another tab of the same browser:
![Screenshot 2021-09-02 at 21-29-39 QuickStatements](https://user-images.githubusercontent.com/465923/131937163-b0a8d0f4-dd5b-4be6-ba5e-4ed5e9250cce.png)

**Comment by Daniel-Mietchen** [comment]
It worked for me intermittently today:
![Screenshot 2021-09-03 at 15-02-33 Scholia](https://user-images.githubusercontent.com/465923/132068824-1d4a630a-dfec-42b5-be33-190f337cd15c.png)

Now, it is broken again. Not sure what the underlying issue is.

**Comment by fnielsen** [comment]
I think this might be related to the use of third-party websites. Sometimes there is a request to csp-report.toolforge.org. I think we unfortunately need to do something about this. Possible implement the functionality serverside.

**Comment by Daniel-Mietchen** [comment]
These third-party services are the subject of 
- #1918

**Comment by fnielsen** [comment]
I have not seen this in a while. The example works:
https://scholia.toolforge.org/doi/10.1080/09589236.2015.1087309
