### ISSUE TITLE
Better or fix issue template: bug report and feature request is not shown

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1740]
#1603 introduced an issue template. In the directory https://github.com/WDscholia/scholia/tree/master/.github/ISSUE_TEMPLATE there are three files, but on the GitHub issue page there is only shown the question line while neither but report nor feature requests are not shown. 

I would have expected that a but report and a feature request option was available on https://github.com/WDscholia/scholia/issues/new/choose

**Comment by fnielsen** [comment]
There is some information here https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository but this is about yaml files while the introduced files are markdown...

**Comment by fnielsen** [comment]
More information here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository but still not clear why it does not work.

**Comment by Daniel-Mietchen** [comment]
I think this boils down to renaming the .md files by dropping the leading underscore.

**Comment by Daniel-Mietchen** [comment]
Here is an example repo without yaml file:
- https://github.com/kubernetes-client/python/issues/new/choose
- https://github.com/kubernetes-client/python/tree/master/.github/ISSUE_TEMPLATE

**Comment by Daniel-Mietchen** [comment]
I'll remove the leading underscores and see what that gives.

**Comment by fnielsen** [comment]
I have asked at https://stackoverflow.com/questions/70659123/only-one-issue-template-is-displayed-on-github-though-multiple-issue-templates-m

**Comment by fnielsen** [comment]
> I'll remove the leading underscores and see what that gives.

Yeah, I had that notion too, but they all have underscores, so ...!?

The label/labels did not fix the problem https://github.com/WDscholia/scholia/commit/29606398c0c69b851052537ffca7363efc30c778

**Comment by fnielsen** [comment]
#1742 did not fix the issue

**Comment by fnielsen** [comment]
Neither the removal of the underscore or the definition of the 'labels' field helped. Here are the labels field for the feature request defined: https://github.com/WDscholia/scholia/commit/92b1110da82f963fc148b3cca66c850886717bed

**Comment by fnielsen** [comment]
We could try to remove the config.yml file. I am running out of good ideas.

**Comment by Daniel-Mietchen** [comment]
I just followed the instructions in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository , which say that we can create these files via the GitHub GUI.
Did a Test PR

**Comment by fnielsen** [comment]
Perhaps the best would be to revert and then use the settings at https://github.com/WDscholia/scholia/issues/templates/edit ?

**Comment by Daniel-Mietchen** [comment]
That's an option too. Your choice. Happy to fill in the forms either way.

**Comment by Daniel-Mietchen** [comment]
I just tested it in another repo - works fine: https://github.com/Daniel-Mietchen/events/issues/new/choose

**Comment by fnielsen** [comment]
It now works at: https://github.com/WDscholia/scholia/issues/new/choose

Interestingly the markdown files were created but no config.yml file. Perhaps it was the config file that should have been erased.

**Comment by fnielsen** [comment]
That was a hard one ... :(
