### ISSUE TITLE
Have the ISSUE_TEMPLATE chooser show all template options

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1741]
## Context

Right now, the template chooser only shows one option, even though we have three templates

## Feature request

Adapt config.yml to include all options

**Comment by fnielsen** [comment]
This is the same as #1740

**Comment by Daniel-Mietchen** [comment]
I think #1740 is about the template md files in the ISSUE TEMPLATES directory, whereas the template chooser is in the yaml file, and we maybe do not need it at this point. See the kubernetes example I gave in the other thread.

**Comment by fnielsen** [comment]
Ok, maybe I have misunderstood functionality. The config file does not say anything about the questions.md file. 

From https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository I read "When you add a manually-created issue template to your repository, project contributors will automatically see the template's contents in the issue body."

But maybe it is a problem with the config.yml file.
