### ISSUE TITLE
'cito' button on the top of the page jumps and has a different size than the other button

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1756]
**Describe the bug**
* 'cito' button on the top of the page jumps 
* 'cito' button has a different size than the other button ("venue")

**To Reproduce**
1. Go to https://scholia.toolforge.org/venue/Q6294930/cito
2. Click on 'cito' button

Cito button may jump back and forth on the line. It apparently occurs randomly.

**Expected behavior**

**Screenshots**
![billede](https://user-images.githubusercontent.com/484028/149820458-9d58be8e-ad08-4feb-904e-d4e66b536611.png)
![billede](https://user-images.githubusercontent.com/484028/149820505-114141a6-f118-43e3-a0b4-8b5cb89e9e81.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser Firefox
 - Version 96.0

**Smartphone (please complete the following information):**

**Comment by egonw** [comment]
I think https://github.com/WDscholia/scholia/pull/1613 was written to make the subpages obsolete and may actually solve this issue in the process.
