### ISSUE TITLE
Wrong link from curation page to Wikidata entry

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1775]
**Describe the bug**
On curation pages, there is an incorrect link intended to go to the corresponding item's Wikidata page.

**To Reproduce**
1. Go to any curation page, e.g. https://scholia.toolforge.org/topic/Q202864/curation
2. Click on the link after "in this case, ", i.e. https://www.wikidata.org/Q202864 for the above example.
3. See error

**Expected behavior**

The link should go to https://www.wikidata.org/wiki/Q202864 (as the link from the H1 header, here "Zika virus (Q202864)") or perhaps better to https://www.wikidata.org/entity/Q202864 (to allow for content negotiation).

**Screenshots**

![Screenshot from 2022-01-28 00-22-48](https://user-images.githubusercontent.com/465923/151460256-69661d77-4c38-4b16-a022-7beb891ca91c.png)

**Additional context**

This is closely related to 
- #1770 

Both have been introduced with the creation of q_curation.html, as per https://github.com/WDscholia/scholia/commit/420b663cd3f5ce60d0a6c3f0bfef9d93f361ccde .

**Comment by bittu426** [comment]
Hey Hi. I'm interested to work on this issue. Can you please assign me to this? Thank you.
