### ISSUE TITLE
The image on top of a profile's page should link to the file's page on Commons

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1778]
**Describe the bug**
The image on top of a profile's page should link to the file's page on Commons

**To Reproduce**
1. Go to a profile for an item with an image, e.g. https://scholia.toolforge.org/topic/Q1659584
2. Click on the image
3. Notice that it does not point to https://commons.wikimedia.org/wiki/File:ImageJScreenshot.png

**Expected behavior**
It should point to https://commons.wikimedia.org/wiki/File:ImageJScreenshot.png .

**Screenshots**

![Screenshot from 2022-01-28 01-09-17](https://user-images.githubusercontent.com/465923/151464614-8d63aeba-05fb-435c-b168-ca87e0da2016.png)

**Comment by bittu426** [comment]
Hello, I'm Chaitanya and I've been asked to contribute to an open-source project for my Software Development course. I'm very interested to work on this issue and it'd be great if I could be assigned to this. Thank you so much.

**Comment by Daniel-Mietchen** [comment]
Welcome, @bittu426 &mdash; sure, feel free to give it a try. A good starting point is https://github.com/WDscholia/scholia/blob/9657b8cbb1cd9fb8deb2c8a565732835d99baaad/scholia/app/templates/base.html#L700 .

**Comment by Daniel-Mietchen** [comment]
@bittu426 Do you have any news on this?

**Comment by bittu426** [comment]
Hi @Daniel-Mietchen thank you so much for following up. I've cloned and started working on it. It took me some time to figure it out as this is my first time working. I still haven't tested it on my system. I will give you an update once I test my work on my system. Thank you

**Comment by Daniel-Mietchen** [comment]
@bittu426 Can you provide an update please?

**Comment by bittu426** [comment]
I have successfully tested it in my local environment and successfully implemented it.  Now every image is pointing to their respective Commons webpage. I raised a pull request. Please review and merge. the changes. Thank you
