### ISSUE TITLE
Special search on author aspect does not work

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1799]
**Describe the bug**
Special search on author aspect does not work. The two edit fields do not respond.

**To Reproduce**
1. Go to https://scholia.toolforge.org/author/ 
2. Click on one of the text fields in "Example profiles" or "Comparisons".
3. Nothing happens.

**Expected behavior**
The interface should search

**Additional context**
This issue might result from the introduction of https://github.com/WDscholia/scholia/pull/1650

**Comment by fnielsen** [comment]
There is a Javascript error: "Uncaught TypeError: $(...).select2 is not a function"

**Comment by WolfgangFahl** [comment]
https://select2.org/ needs to be loaded e.g.
with
```javascript
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

```

**Comment by WolfgangFahl** [comment]
Refactoring the code to have the SQL autocomplete query be in a widget would probably be helpful here to get more cases working where such a feature might be useful.

**Comment by fnielsen** [comment]
What is "SQL autocomplete"?
