### ISSUE TITLE
Image file name is not escaped

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1800]
**Describe the bug**

**To Reproduce**
1. Go to https://scholia.toolforge.org/topic/Q42133786
2. No image is shown.

**Expected behavior**
A image should be shown.

**Additional context**
"?" should be escaped to "%3F", - and perhaps other characters should be escaped too.

**Comment by Sync271** [comment]
In the line below, 
https://github.com/WDscholia/scholia/blob/564fbf628da7cecdcbe28212b9d0115881fd24b3/scholia/app/templates/base.html#L139
when `encodeURI()` is replaced with `encodeURIComponent()`, the expected output should be:
**"Can_You_Hear_Me_Now%3F_-MeToo_(39787332552).jpg"**
but on gitpod it returns:
**"Can_You_Hear_Me_Now%3F_-MeToo_%2839787332552%29.jpg"**
where  `"("` and `")"` also escape along with `"?"`

**Comment by fnielsen** [comment]
Maybe there is too much escaping...?

**Comment by fnielsen** [comment]
Running now, e.g., https://scholia.toolforge.org/topic/Q42133786
