### ISSUE TITLE
WDQS scaling issues meetings in February

### ISSUE THREAD

**Issue by dpriskorn** [WDscholia/scholia#1806]
## Context

https://lists.wikimedia.org/hyperkitty/list/wikidata@lists.wikimedia.org/thread/KPA3CTQG2HCJO55EFZVNINGVFQJAHT4W/

## Question
Is it a good idea to participate and deliver our perspective?

**Comment by Daniel-Mietchen** [comment]
@dpriskorn Probably yes.

For the record, this relates to 
- #1721 
and we are having a hackathon next week, as per
- #1807

**Comment by fnielsen** [comment]
# WDQS scaling community meeting 1/2: SPARQL query features*
      - Thursday, February 17 · 18:00 UTC
# WDQS scaling community meeting 2/2: RDF store backend needs*
      - Monday, February 21 · 18:00 UTC

**Comment by Daniel-Mietchen** [comment]
See also https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Feb_2022_scaling_community_meetings

**Comment by dpriskorn** [comment]
I created the request for bot flag for So9qBot earlier and met resistance presumably because of fear of breakage/overloading blazegraph. 
Since I raised the issue in the Wikidata Telegram channel a lot has happened. WMF started analyzing the issue in depth and now that we have a disaster playbook and WMF began the process of evaluating alternatives to blazegraph. 
I intend to finish the original idea of asseeibot so that it can add new items for each DOI found in Wikipedia, which we are currently missing in Wikidata. 
This will increase the number of scientific items by 10-15% but at a pace the community can control. 
If all direct references to the DOIs found are also imported the number of items will probably double to 80M over time.

I also plan to create an importer for refcat from IA which have a lot of DOIs also. This will bring our collection of papers up to a level around 100M in total. 

Nobody knows if these to imports will take blazegraph past the breaking point, but that is not a big issue since only 1% of all queries are affected. 

If it breaks the playbook is enacted and we can continue working, but without SPARQL support from WMF during an interim period. 
This will affect Scholia a lot. We would have to set up our own sparql endpoint with the data somewhere.

**Comment by Daniel-Mietchen** [comment]
The notes from the first meeting on Thursday Feb 17 about SPARQL query features sit at https://etherpad.wikimedia.org/p/R5n382Ld0Vvykc7Ak3iH .

I could not attend but @fnielsen and @dpriskorn did, and I went through the notes later on, particularly adding examples of Scholia queries that time out:
* https://scholia.toolforge.org/author/Q9047#academic-tree (usually works, but at its limits)
* https://scholia.toolforge.org/author/Q46826387#publications-per-year
* https://scholia.toolforge.org/author/Q46826387#coauthors
* https://scholia.toolforge.org/author/Q55004959#list-of-publications
* https://scholia.toolforge.org/author/Q55004959#publications-per-year
* https://scholia.toolforge.org/author/Q46826387/missing#missing-coauthor-items
* https://scholia.toolforge.org/authors/Q53405108,Q53382329,Q57956212,Q42225039,Q57956362,Q42666666,Q53407393#co-author
* https://scholia.toolforge.org/country/Q35
* https://scholia.toolforge.org/country/Q668
* https://scholia.toolforge.org/location/Q583725#nearby-locations-as-topics-in-works
* https://scholia.toolforge.org/location/Q84/topic/Q41112
* https://scholia.toolforge.org/organization/Q13371
* https://scholia.toolforge.org/organization/Q13371##employees-and-affiliated
* https://scholia.toolforge.org/organization/Q13371#most-cited-papers
* https://scholia.toolforge.org/organizations/Q1269766,Q193196#citations-per-year
* https://scholia.toolforge.org/organizations/Q1269766,Q193196#citations-to-works
* https://scholia.toolforge.org/publisher/Q746413#citations-works
* https://scholia.toolforge.org/sponsor/Q60346#project-budgets
* https://scholia.toolforge.org/topic/Q15#publications-per-year
* https://scholia.toolforge.org/topic/Q41719#author-scores
* https://scholia.toolforge.org/topic/Q41719#coauthor-graph
* https://scholia.toolforge.org/topic/Q41719#co-occurring
* https://scholia.toolforge.org/topic/Q41719#co-occurring-map
* https://scholia.toolforge.org/topic/Q41719#publications-per-year
* https://scholia.toolforge.org/topic/Q180556#most-cited-authors
* https://scholia.toolforge.org/topic/Q180556#top-cited
* https://scholia.toolforge.org/topic/Q1492760#author-scores
* https://scholia.toolforge.org/topic/Q1492760#country-citation-graph
* https://scholia.toolforge.org/topic/Q1492760#publications-per-year
* https://scholia.toolforge.org/topic/Q18123741#publications-per-year
* https://scholia.toolforge.org/topic/Q181600/missing#missing-author-items
* https://scholia.toolforge.org/topic/Q1492760/missing#missing-author-items
* https://scholia.toolforge.org/venue/Q26150#recently-published-works
* https://scholia.toolforge.org/venue/Q26535#recently-published-works
* https://scholia.toolforge.org/venue/Q939416#recently-published-works
* https://scholia.toolforge.org/venue/Q564954#articles-by-intention
* https://scholia.toolforge.org/venues/Q180445,Q192864,Q1146531 (all three queries)
* https://scholia.toolforge.org/P577 (first two queries)

The next meeting on RDF store backend needs is today at 18:00 UTC, and I'll try to be there.

**Comment by Daniel-Mietchen** [comment]
The WDQS scaling call just ended, and I found it useful. Notes in https://etherpad.wikimedia.org/p/yPUhyhbmXglC_Magx0Go .

**Comment by fnielsen** [comment]
Blogpost: "[What SPARQL keywords do we use in Scholia?](https://finnaarupnielsen.wordpress.com/2022/02/21/what-sparql-keywords-do-we-use-in-scholia/)"

**Comment by Daniel-Mietchen** [comment]
Official summary: https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/WDQS-scaling-update-feb-2022
