### ISSUE TITLE
On curation page for ```use```, add panel for missing author name strings

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1808]
[Sample query](https://query.wikidata.org/#%23%20tool%3A%20scholia%0ASELECT%0A%20%20%23%20Number%20of%20works%20with%20the%20author%0A%20%20%3Fcount%0A%0A%20%20%23%20Author%20score%20-%203%20points%20for%20authoring%20a%20work%2C%201%20for%20being%20cited%0A%20%20%3Fscore%0A%0A%20%20%23%20Author%20as%20a%20string%0A%20%20%3Fauthor%0A%0A%20%20%23%20Build%20URL%20to%20the%20Author%20disambiguator%20tool%0A%20%20%28CONCAT%28%0A%20%20%20%20%20%20%27https%3A%2F%2Fauthor-disambiguator.toolforge.org%2Fnames_oauth.php%3Fdoit%3DLook%2Bfor%2Bauthor%26name%3D%27%2C%0A%20%20%20%20%20%20ENCODE_FOR_URI%28%3Fauthor%29%29%20AS%20%3Fresolver_url%29%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fwork%20WHERE%20%7B%0A%20%20%20%20%3Fwork%20p%3AP2283%20%7C%20p%3AP4510%20%3Fuse_statement%20.%0A%20%20%20%20%3Fuse_statement%20%28ps%3AP2283%20%7C%20ps%3AP4510%29%20%2F%20%28wdt%3AP279%2a%29%20wd%3AQ70357595%20.%0A%20%20%20%20OPTIONAL%20%7B%20%3Fuse_statement%20prov%3AwasDerivedFrom%2Fpr%3AP1683%20%3Fquote_%20.%20%7D%0A%20%20%7D%0A%7D%20AS%20%25works%0AWITH%20%7B%0A%20%20SELECT%0A%20%20%20%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount%29%0A%20%20%20%20%3Fauthor%0A%20%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20%3Fwork%20wdt%3AP2093%20%3Fauthor%20.%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthor%0A%7D%20AS%20%25result%0A%0A%23%20Generate%20a%20score%20for%20each%20author%0AWITH%20%7B%0A%20%20SELECT%20%28SUM%28%3Fscore_%29%20AS%20%3Fscore%29%20%3Fauthor%0A%20%20WHERE%20%7B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%23%20Assign%20them%203%20points%20if%20they%20are%20an%20author%20of%20a%20work%20on%20the%20subject%0A%20%20%20%20%20%20SELECT%20%283%20AS%20%3Fscore_%29%20%3Fauthor%20%3Fwork%20WHERE%20%7B%0A%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP2093%20%3Fauthor%20.%0A%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP921%2Fwdt%3AP279%2a%20wd%3AQ70357595%20.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%23%20Assign%20them%201%20point%20if%20they%20are%20the%20author%20of%20a%20work%20that%20is%20cited%20by%20a%20work%20on%20the%20subject%0A%20%20%20%20%20%20SELECT%20%281%20AS%20%3Fscore_%29%20%3Fauthor%20%3Fwork%20WHERE%20%7B%0A%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP2093%20%3Fauthor%20.%0A%20%20%20%20%20%20%20%20%3Fciting_work%20wdt%3AP2860%20%3Fwork%20.%0A%20%20%20%20%20%20%20%20%3Fciting_work%20wdt%3AP921%2Fwdt%3AP279%2a%20wd%3AQ70357595%20.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthor%0A%7D%20AS%20%25scores%0A%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%0A%20%20INCLUDE%20%25scores%0A%0A%20%20%23%20Label%20the%20result%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22%20.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29%20DESC%28%3Fscore%29%0ALIMIT%20500%0A) for Jupyter notebook (Q70357595):

```SPARQL

# tool: scholia
SELECT
  # Number of works with the author
  ?count

  # Author score - 3 points for authoring a work, 1 for being cited
  ?score

  # Author as a string
  ?author

  # Build URL to the Author disambiguator tool
  (CONCAT(
      'https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=',
      ENCODE_FOR_URI(?author)) AS ?resolver_url)
WITH {
  SELECT DISTINCT ?work WHERE {
    ?work p:P2283 | p:P4510 ?use_statement .
    ?use_statement (ps:P2283 | ps:P4510) / (wdt:P279*) wd:Q70357595 .
    OPTIONAL { ?use_statement prov:wasDerivedFrom/pr:P1683 ?quote_ . }
  }
} AS %works
WITH {
  SELECT
    (COUNT(?work) AS ?count)
    ?author
  WHERE {
    INCLUDE %works
    ?work wdt:P2093 ?author .
  }
  GROUP BY ?author
} AS %result

# Generate a score for each author
WITH {
  SELECT (SUM(?score_) AS ?score) ?author
  WHERE {
    {
      # Assign them 3 points if they are an author of a work on the subject
      SELECT (3 AS ?score_) ?author ?work WHERE {
        ?work wdt:P2093 ?author .
        ?work wdt:P921/wdt:P279* wd:Q70357595 .
      }
    }
    UNION
    {
      # Assign them 1 point if they are the author of a work that is cited by a work on the subject
      SELECT (1 AS ?score_) ?author ?work WHERE {
        ?work wdt:P2093 ?author .
        ?citing_work wdt:P2860 ?work .
        ?citing_work wdt:P921/wdt:P279* wd:Q70357595 .
      }
    }
  }
  GROUP BY ?author
} AS %scores

WHERE {
  INCLUDE %result
  INCLUDE %scores

  # Label the result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}
ORDER BY DESC(?count) DESC(?score)
LIMIT 500

```

**Comment by fnielsen** [comment]
Running now, e.g., https://scholia.toolforge.org/use/Q24901201/curation
