### ISSUE TITLE
Add badges to readme

### ISSUE THREAD

**Issue by WolfgangFahl** [WDscholia/scholia#1818]
see https://github.com/somnathrakshit/geograpy3 for how the  badge panel might look

**Comment by Daniel-Mietchen** [comment]
The first badge &mdash; to indicate whether the website is up or down &mdash; was addressed via
- #1821

**Comment by fnielsen** [comment]
I have now added some. If there is any specific badge, I can add them. Note that we are still not on PYPI.

**Comment by WolfgangFahl** [comment]
https://github.com/somnathrakshit/geograpy3/blob/master/.github/workflows/upload-to-pypi.yml has the script for uploading to pypi automatically on each release.
note the
```
TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
```
for the necessary credentials
