### ISSUE TITLE
Adding the PPN ID to events

### ISSUE THREAD

**Issue by tholzheim** [WDscholia/scholia#1844]
[//]: # "==Do not write above this line==
A Scholia aspect is used to profile the target item in a specific way, e.g.
https://scholia.toolforge.org/topic/Q202864
profiles Q202864 (Zika virus) as a topic.
A query within a given aspect is called a panel. Please use the ``Add new panel to ... aspect ...`` template to propose a new panel for an aspect.
==Write below this line=="
As a starting point for https://github.com/WDscholia/scholia/issues/1576. 
Adding a wikidata bot to the ConferenceCorpus (https://github.com/WolfgangFahl/ConferenceCorpus/issues/12) that based on a TIBKat dump adds the [PPN ID](https://www.wikidata.org/wiki/Property:P6721) to the corresponding events.

**Comment by Daniel-Mietchen** [comment]
@tholzheim Can you be a bit more specific? Do you mean you want to add the PPN ID to https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/event.html ?

**Comment by tholzheim** [comment]
Moved issue to  #1846

**Comment by Daniel-Mietchen** [comment]
Adding a pointer to 
- #1807 

which serves to keep an overview of things we worked on during the hackathon.
