### ISSUE TITLE
In journal aspect, the CiTO section is not displayed

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1856]
**Describe the bug**

In https://scholia.toolforge.org/venue/Q6294930 , the [#citation-typing-ontology](https://scholia.toolforge.org/venue/Q6294930#citation-typing-ontology) section is displayed in the Table of Contents and has the expected section link but that section is missing. 

**To Reproduce**
1. Go to a venue page
2. Click on the "[Citation Typing Ontology](https://scholia.toolforge.org/venue/Q6294930#citation-typing-ontology)" link in the Table of contents
3. Scroll down to [Articles citing retracted articles](https://scholia.toolforge.org/venue/Q6294930#articles-citing-retracted-articles) and check what is above &mdash; it is the "Citing venues" section.

**Expected behavior**

CiTO panels should be there, as per https://github.com/WDscholia/scholia/pull/1613#issuecomment-1039265578 (which has screenshots).

**Additional context**
This is related to 
- #1613

Pinging @carlinmack @fnielsen

**Comment by Daniel-Mietchen** [comment]
Current screenshot for https://scholia.toolforge.org/venue/Q6294930: 

![Screenshot 2022-02-16 at 21-09-29 Journal of Cheminformatics - Scholia](https://user-images.githubusercontent.com/465923/154350464-1c0a838f-e874-4a0b-be6e-cd968343eeeb.png)

**Comment by fnielsen** [comment]
Could it be a cache issue? Can you do a cache refresh? I am seeing https://scholia.toolforge.org/venue/Q6294930#citation-typing-ontology

**Comment by Daniel-Mietchen** [comment]
Yes, seems to have been a cache issue. Thanks for checking.
