### ISSUE TITLE
Bad links on some statement values

### ISSUE THREAD

**Issue by pigsonthewing** [WDscholia/scholia#186]
On, for example https://tools.wmflabs.org/scholia/work/Q19966966 under the "Supports the following statement(s)" heading, some items in the "value" column are not linked properly. An example is "Trigonopterus zygops" which should be linked to https://www.wikidata.org/wiki/Q15613085 but is actually linked to https://tools.wmflabs.org/scholia/

**Comment by egonw** [comment]
@pigsonthewing, nice catch!

**Comment by egonw** [comment]
I believe this is fixed by now (please reopen if I am wrong):

![image](https://github.com/WDscholia/scholia/assets/26721/95318684-644e-4bc8-9710-1ce4923b419e)
