### ISSUE TITLE
Work curation panels are missing

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1883]
**Describe the bug**
Work curation panels are missing

**To Reproduce**
1. Go to https://scholia.toolforge.org/work/Q110992388/curation

**Expected behavior**
I expected to see tables there.

**Additional context**
The HTML seems to be missing some `<div>`s

**Comment by fnielsen** [comment]
We do not have work curation. This should be a feature request.

**Comment by Daniel-Mietchen** [comment]
Here is a query suggestion:
- #1860 

I have been using others too - will dig them out and post here.

**Comment by Daniel-Mietchen** [comment]
Here is another one:
- #1901

**Comment by Daniel-Mietchen** [comment]
[Here](https://query.wikidata.org/#PREFIX%20target%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ27350225%3E%0A%0ASELECT%0A%20%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount%29%20%0A%20%20%3Fauthor_name%20%0A%20%20%28CONCAT%28%22https%3A%2F%2Fauthor-disambiguator.toolforge.org%2Fnames_oauth.php%3Fdoit%3DLook%2Bfor%2Bauthor%26name%3D%22%2C%20%0A%20%20%20%20%20%20%20%20%20%20ENCODE_FOR_URI%28%3Fauthor_name%29%29%20AS%20%3Fauthor_resolver_url%29%20%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fauthors%20WHERE%20%7B%0A%20%20%20%20target%3A%20wdt%3AP50%20%3Fauthors%20.%0A%20%20%7D%0A%20%20LIMIT%20200%20%20%0A%7D%20AS%20%25works%0AWHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fauthor_name%20WHERE%20%7B%0A%20%20%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%7B%20%3Fauthors%20skos%3AaltLabel%20%3Fauthor_name_.%20%7D%0A%20%20%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%20%20%7B%20%3Fauthors%20rdfs%3Alabel%20%3Fauthor_name_.%20%7D%0A%20%20%20%20%20%20%20%20BIND%28STR%28%3Fauthor_name_%29%20AS%20%3Fauthor_name%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%3Fauthor_statement%20ps%3AP50%20%3Fauthors%3B%0A%20%20%20%20%20%20%20%20%20%20pq%3AP1932%20%3Fauthor_name.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fwork%20wdt%3AP2093%20%3Fauthor_name.%20%7D%0A%7D%0AGROUP%20BY%20%3Fauthor_name%0AORDER%20BY%20DESC%20%28%3Fcount%29%0A%0A%0A) is one for author name strings on papers that share authors with the target paper:

```SPARQL
PREFIX target: <http://www.wikidata.org/entity/Q27350225>

SELECT
  (COUNT(?work) AS ?count) 
  ?author_name 
  (CONCAT("https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=", 
          ENCODE_FOR_URI(?author_name)) AS ?author_resolver_url) 
WITH {
  SELECT DISTINCT ?authors WHERE {
    target: wdt:P50 ?authors .
  }
  LIMIT 200  
} AS %works
WHERE {
  {
    SELECT DISTINCT ?author_name WHERE {
      INCLUDE %works
      {
        { ?authors skos:altLabel ?author_name_. }
        UNION
        { ?authors rdfs:label ?author_name_. }
        BIND(STR(?author_name_) AS ?author_name)
      }
      UNION
      {
        ?author_statement ps:P50 ?authors;
          pq:P1932 ?author_name.
      }
    }
  }
  OPTIONAL { ?work wdt:P2093 ?author_name. }
}
GROUP BY ?author_name
ORDER BY DESC (?count)

```
