### ISSUE TITLE
Errata is shown as "preprint of" 

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1886]
**Describe the bug**
Errata is shown as "preprint of"  at least for this example: https://scholia.toolforge.org/work/Q100515601

**To Reproduce**
1. Go to https://scholia.toolforge.org/work/Q100515601
2. Look in datatable

**Expected behavior**
Should not show "preprint of"

**Comment by carlinmack** [comment]
duplicate of #1597

**Comment by egonw** [comment]
Similar problem for retraction notices:

![image](https://user-images.githubusercontent.com/26721/209994591-136a2000-c139-4b62-af4e-0b6264396c07.png)
