### ISSUE TITLE
Better handling of "No data available" cases

### ISSUE THREAD

**Issue by pigsonthewing** [WDscholia/scholia#189]
If I select an item (example: https://tools.wmflabs.org/scholia/topic/Q300915 ) which returns "No data available in table", a large, read "error" banner shows under the "Publications per year" heading.

This may cause consternation to new or naive users, and - particularly if seen during demonstrations - gives the impression that the tool is faulty.

Instead, it would be better to show a more subtle "no data to display" message, without the red, and to reserve the error message for cases where something is really broken.

**Comment by fnielsen** [comment]
Yes. The response, however, comes from WDQS and circumventing will take some work.

**Comment by Daniel-Mietchen** [comment]
There is now a Phabricator ticket for this: https://phabricator.wikimedia.org/T200718 .

**Comment by Daniel-Mietchen** [comment]
There has also been a more detailed discussion at https://github.com/fnielsen/scholia/issues/301 .

**Comment by carlinmack** [comment]
phabricator ticket is closed
