### ISSUE TITLE
In work_data.sparql , add information about resources used

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1895]
i.e. in
https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/work_data.sparql ,
add information pertaining to 
uses ([P2283](https://www.wikidata.org/wiki/Property:P2283))
and/ or 
describes a project that uses ([P4510](https://www.wikidata.org/wiki/Property:P4510)).

**Comment by Daniel-Mietchen** [comment]
For some good items to test this, see
https://scholia.toolforge.org/P2283#item-counts
and
https://scholia.toolforge.org/P4510#item-counts


Note that there are still multiple occurrences of ```{{ q }}``` outside the ```PREFIX```.

**Comment by fnielsen** [comment]
The "data" panel on the "work" aspect now includes a "uses" row, e.g., https://scholia.toolforge.org/work/Q70188422

It was also related to #1962
