### ISSUE TITLE
On curation page for ```use```, add panel for missing topic tags

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1900]
**What kind of panel would you like to add to which Scholia aspect?**

A panel to help curation the information behind https://scholia.toolforge.org/use/Q70357595#topics-of-works-using-the-resource .

**What kind of information should the panel provide, and which of the visualization options (e.g. table, bubble chart, map) should it use?**

Works that have less than two topic tags, e.g. as per
https://scholia.toolforge.org/topic/Q202864/curation#missing-co-topic .

**Which Wikidata entries would be good candidates to explore such visualizations?**

https://scholia.toolforge.org/P4510#property-value-counts

**Anything else?**

**Comment by fnielsen** [comment]
Note I have only been using P4510, - not P2283
