### ISSUE TITLE
Contextualize the lead image

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1902]
**Is your feature request related to a problem? Please describe.**

Example from https://scholia.toolforge.org/taxon/Q752130: 
![Screenshot from 2022-03-08 23-51-08](https://user-images.githubusercontent.com/465923/157339328-23f9bb82-6267-471c-bb1d-6e06ec9be245.png)

The image is there and links to its page on Commons, but it is not contextualized. 

**Describe the solution you'd like**

There are various possible improvements. For instance, we could have a tooltip on mouseover, we could make use of [media legend (P2096)](https://www.wikidata.org/wiki/Property:P2096), we could surface the alt text more prominently and/ or we could frame the image.

**Describe alternatives you've considered**

See above.

**Additional context**

We could perhaps use images as more actively in guiding Scholia users. The mussle image from the example above, for instance, is used on a variety of pages across multiple wikis, and we could try to show/ link to information related to the corresponding items. Besides the item about the mussle itself, that image would thus also lead the user to explore 
-  [biodiversity](https://www.wikidata.org/wiki/Q47041)
- [Fauna of Saskatchewan ](https://www.wikidata.org/wiki/Q5438211)
- [siphon](https://www.wikidata.org/wiki/Q1276903)

![Screenshot 2022-03-08 at 23-59-28 File Dreissena polymorpha jpg - Wikimedia Commons](https://user-images.githubusercontent.com/465923/157340243-b869866c-122b-4b88-939a-25fd6abf44fe.png)

**Comment by fnielsen** [comment]
The `alt` text is present, but does not appear in Firefox, for instance. At least that is what I can check. A text that appear when the most hoovers over the image should be implemented in Javascript is seems.

**Comment by bittu426** [comment]
@fnielsen Can I work on this issue? Thank you in advance.

**Comment by bittu426** [comment]
Hi @Daniel-Mietchen .  I've successfully implemented it and tested it locally. Now a text is displayed whenever we hover the mouse on an image. (contextualized the lead image). I've raised a pull request, Please review and merge the changes. Thank you so much.

**Comment by fnielsen** [comment]
It is now running on Toolforge. Thanks for the PR.
