### ISSUE TITLE
Does Scholia uses WD qualifiers on sparql queries? 

### ISSUE THREAD

**Issue by versant2612** [WDscholia/scholia#1905]
## Context
Many WD Claims have qualifiers, like temporal, location, topic and so on. For example, a researcher can be affiliated to an organization between a period of time. 

## Question
Does Scholia uses WD qualifiers on sparql queries? If yes, can you give an example. I no, why not?

**Comment by fnielsen** [comment]
Example fragment from timeline for an author: 
```sparql
{
    target: p:P166 ?award_statement .
    ?award_statement ps:P166 ?award .
    ?award rdfs:label ?award_label .
    FILTER (lang(?award_label) = 'en')
    BIND(CONCAT("🏆 ",?award_label) AS ?label)
    ?award_statement pq:P585 ?beginning .
}
```
