### ISSUE TITLE
Setup Simolecule on Toolforge

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1920]
**Is your feature request related to a problem? Please describe.**
We do not use Simolecule on the Toolforge instance because of privacy issues. It can generate graphical images of molecules on the fly.

**Describe the solution you'd like**
Simolecule has a Docker image. It was suggested by @egonw  at #1913

It is not immediately clear whether Docker images can run on Toolforge infrastructure though. Toolforge may provide a fixed set of docker images. 

**Describe alternatives you've considered**
P117 can be used is set for some molecules.

**Comment by egonw** [comment]
https://cdkdepict.toolforge.org/ has been set up (ht to taavi)
