### ISSUE TITLE
How to change author names to author with a tool

### ISSUE THREAD

**Issue by WolfgangFahl** [WDscholia/scholia#1922]
## Context
[The paper A selective undo mechanism for graphical user interfaces based on command objects](https://www.wikidata.org/wiki/Q59702273)
has 
[Thomas Berlage](https://www.wikidata.org/wiki/Q111446471) as it's author

There are more Papers by Thomas Berlage that need to be changed from "author name string" to "author". 

Obviously this is just an example for the general author - author-name - paper issue

## Question
Do we have a tool for adding an author and changing the corresponding paper author name strings to author?

**Comment by fnielsen** [comment]
I am not sure what you mean. The "Improve data" on https://scholia.toolforge.org/author/Q111446471 leads to our curation page https://scholia.toolforge.org/author/Q111446471/curation where there is one or more links to Arthur P. Smith's author-disambiguator tool: https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=Thomas%20Berlage Is that what you mean?

**Comment by WolfgangFahl** [comment]
@fnielsen - Yes Finn this goes into the right direction. It's just that i never tried "improve data" since it didn't know what it does and what options it has. The tool it's self seems to need some sort of authentication and that's the point where i am stuck now.

**Comment by WolfgangFahl** [comment]
I was now able to successfully run thru a batch and the experience was not too bad.
https://github.com/arthurpsmith/author-disambiguator/ seems to be the source code of the tool which answers my question thank you!

**Comment by WolfgangFahl** [comment]
I'll talk to Daniel next week on whether it's worthwhile to pursue a more general disambiguation approach. I need to disambiguate events and eventseries for my work any way and why not refator the whole show to have the lessons learned from the past few years guide an improved version ...

**Comment by fnielsen** [comment]
@Daniel-Mietchen recently implemented a more general approach but not so tailored. He did it for the taxon aspect, e.g., https://scholia.toolforge.org/taxon/Q25485/curation This approach requires a user to go to WDQS, edit the query, execute it, copy-and-paste the result into quickstatements (with possible edits) and let that service enter the data.
