### ISSUE TITLE
command line tools via console_scripts

### ISSUE THREAD

**Issue by WolfgangFahl** [WDscholia/scholia#1935]
**Is your feature request related to a problem? Please describe.**
currently scholia command line features need to be called via the python interpreter

**Describe the solution you'd like**
pip install has a [console_scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) feature that allows to wrap python command line access as native command line scripts

the scripts hould have a proper --help usage description

**Describe alternatives you've considered**
Supplying shell scripts our selves

**Additional context**
What would be a list of features that are worthwhile to have their own command line?

- starting the webserver runserver
- lookups such as twitter-to-q

**Comment by fnielsen** [comment]
@cthoyt added functionality for this in 2021, see https://github.com/WDscholia/scholia/blob/master/setup.cfg

Installation with `python3 -m pip install git+https://github.com/WDscholia/scholia` will get you a command line.

**Comment by fnielsen** [comment]
For instance, 
```bash
$ scholia
Usage:
  scholia arxiv-to-quickstatements [options] <arxiv>
  scholia orcid-to-q <orcid>
  scholia string-to-type <string>
  scholia run
```

**Comment by WolfgangFahl** [comment]
This is not what the issue is about. The issue is about installing the command line on pip install

**Comment by fnielsen** [comment]
But if you install scholia with pip now, you will get the the command line. I can run scholia as a console script:
```bash
$ scholia --help
query.

Usage:
  scholia arxiv-to-quickstatements [options] <arxiv>
  scholia orcid-to-q <orcid>
  scholia string-to-type <string>
  scholia run

Options:
  -o --output=file  Output filename, default output to stdout

Examples
--------
  $ python -m scholia orcid-to-q 0000-0001-6128-3356
  Q20980928

References
----------
  https://wikidata-todo.toolforge.org/quick_statements.php
```

**Comment by cthoyt** [comment]
I’m also unsure what the remaining issue is. Seems like @fnielsen has explained nicely how to install and run the vanity cli (in the mean time while potentially considering posting to PyPI)

**Comment by WolfgangFahl** [comment]
This is what the current install result is which is indeed fully compatbile with the console_scripts approach.
```bash
#!/opt/anaconda3/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from scholia.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

https://github.com/WDscholia/scholia/blob/master/setup.cfg seems to hide the details of the setup. 

Thank you for pointing out how scholia is configured to achieve this.

**Comment by WolfgangFahl** [comment]
See #1937 for the plural "command line tools" to clarify that it might be worthwhile to have individual commands instead of a single scholia wrapper so make sure the arguments of each command may be well documented in different.
