### ISSUE TITLE
Images in TIF format do not display properly

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1940]
**Describe the bug**

**To Reproduce**
1. Go to a profile for an item that has an image in tif format, e.g. https://scholia.toolforge.org/work/Q22810003
1. Instead of the image, just its file name is displayed and not even linked.

**Expected behavior**

Some representation of the image should be visible

**Screenshots**

![Screenshot from 2022-04-10 09-37-20](https://user-images.githubusercontent.com/465923/162607879-5c54e64c-e030-4bc0-a950-2311686f196d.png)

**Comment by fnielsen** [comment]
This does not show in my browser: https://upload.wikimedia.org/wikipedia/commons/3/38/Parasite150062-fig1_Torrestrongylus_tetradorsalis_(Nematoda%2C_Trichostrongylidae%2C_Anoplostrongylinae)_FIGS_1-12.tif

**Comment by fnielsen** [comment]
The above file shows in Ubuntu image viewer.

**Comment by carlinmack** [comment]
The images displayed on [Commons](https://commons.wikimedia.org/wiki/File:Parasite150062-fig1_Torrestrongylus_tetradorsalis_(Nematoda,_Trichostrongylidae,_Anoplostrongylinae)_FIGS_1-12.tif) is a JPG preview of the TIF file, which has two pages.  TIFF files aren't supported on the web anymore

![image](https://user-images.githubusercontent.com/6676843/174456673-12fcf3b1-8ea6-4340-93a9-10e29021fc8f.png)

> https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#tiff_tagged_image_file_format

I'll make a PR to access the jpg preview :)
