### ISSUE TITLE
Chemical: "Related Compounds" renaming

### ISSUE THREAD

**Issue by Adafede** [WDscholia/scholia#1942]
## Context
I was browsing some info about https://scholia.toolforge.org/chemical/Q3613679 and noticed for the first time the `Related Compounds` panel.

## Question
- Could we rename it more precisely? The result of the [chemical_related.sparql](https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/chemical_related.sparql) are **known stereoisomers** which is more defined than `Related compounds`.

## Suggestion
In case the initial goal was not only to list *known stereoisomers* but `related compounds`(related, how? structurally?), a possibility would be to use the [Sachem cartridge](https://doi.org/10.1186/s13321-018-0282-y). (example: [https://w.wiki/4VG4](https://w.wiki/4VG4))

@egonw

**Comment by egonw** [comment]
If not mistaken the isomer info is also part in the second InChIKey layer. So, it will also show compounds with the same stereochemistry, same connectivity, but just different isotopes.

**Comment by Adafede** [comment]
So `Compounds with same connectivity`?
