### ISSUE TITLE
Fix code quality as reported on lgtm

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1945]
**Describe the bug**
https://lgtm.com/projects/g/WDscholia/scholia?mode=list reports poor code quality on various parts of Scholia. 

This is both in the Python and the Javascript code.

**Comment by carlinmack** [comment]
Quite a few of these look serious!

**Comment by carlinmack** [comment]
LGTM is closing in December https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

I'll look into this

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/195083142-51aae2da-54f0-45c1-b619-8a81ca58f838.png)

I'll make a PR per class of error for ease of reviewing, and list them here too:

- [x] 2 alerts of Flask app is run in debug mode across 2 files — I think this is okay unless we are running in debug mode in production?
- [ ] 1 alert of Suspicious unused loop iteration variable in _version.py
- [ ] 1 alert of Malformed id attribute in author.html
- [ ] 3 alerts of Missing variable declaration in scholia.js
- [ ] 1 alert of Polynomial regular expression used on uncontrolled data in arxiv.py
- [ ] 8 alerts of Unnecessary 'else' clause in loop across 2 files
- [ ] 4 alerts of Module is imported with 'import' and 'import from' across 4 files
- [ ] 3 alerts of Semicolon insertion in scholia.js
- [ ] 2 alerts of Unused variable, import, function or class in scholia.js

**Comment by carlinmack** [comment]
It is easy to fix this error by replacing `i` with `_`:

![image](https://user-images.githubusercontent.com/6676843/195096173-5de037df-bd4c-4d32-ad1e-0f55c576deca.png)

However I think that the for loop could be replaced with its body

https://github.com/WDscholia/scholia/blob/master/scholia/_version.py#L498-L499

**Comment by carlinmack** [comment]
I've also read into this and I don't think it's a problem for us

![image](https://user-images.githubusercontent.com/6676843/195666485-0a6602ce-3a82-44f2-8f53-8b3cd1edf06e.png)

Perhaps we could use `search` instead: "[`findall()` matches all occurrences of a pattern, not just the first one as `search()` does.](https://docs.python.org/3/library/re.html#finding-all-adverbs)" but I don't think it's that important

**Comment by carlinmack** [comment]
All issues have been been considered :) See above

**Comment by carlinmack** [comment]
All PRs are merged and LGTM is no longer a company. Closed :)
