### ISSUE TITLE
Setup from DOI with empty title errs

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1971]
**Describe the bug**
Setup from DOI with empty title errs. The quickstatements are empty and the quickstatement tools does not like that.

BoolQ: Exploring the Surprising Difficulty of Natural Yes/No Questions Q112075162
10.18653/V1/N19-1300

**To Reproduce**
The article is already entered in Wikidata, so difficult to reproduce.

**Expected behavior**
Title should be setup or that should be no quickstatements for the title.

**Comment by larsgw** [comment]
> The quickstatements are empty and the quickstatement tools does not like that.

I only see empty values in the label and P1476 statement, is that what you mean?

**Comment by fnielsen** [comment]
> I only see empty values in the label and P1476 statement, is that what you mean?

Yes, I think so. :)

**Comment by fnielsen** [comment]
This is now fixed in citation-js: https://github.com/citation-js/plugin-quickstatements/issues/8
