### ISSUE TITLE
Software aspect fails to recognize software dependencies

### ISSUE THREAD

**Issue by bluerasberry** [WDscholia/scholia#1972]
**What query is this about**
Please provide a link to a Scholia profile and the appropriate section heading and/ or .sparql file.
https://scholia.toolforge.org/software/Q107381592#software-dependencies
https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/software_software-dependencies.sparql

**What change do you propose, and why?**
This query fails to identify software dependencies which are labeled in the Wikidata item. See for example
https://www.wikidata.org/w/index.php?title=Q25304899&oldid=1642351647#P1547
Where there are four values for https://www.wikidata.org/wiki/Property:P1547, "depends on software"

![image](https://user-images.githubusercontent.com/15927589/169390762-27956a3d-015f-4533-bec1-cd6613e7030e.png)

![image](https://user-images.githubusercontent.com/15927589/169392180-76b2a180-71ad-4772-a918-1e6186ca1b6e.png)

**Anything else to consider here?**
Error is likely in the SPARQL query

**Comment by fnielsen** [comment]
I have recently merged two items that both were Statsmodels. Some of the old likes are not yet relinked. I suppose there is a bot doing that and dependencies will eventually show up. The real statsmodel is https://scholia.toolforge.org/software/Q25304899

Open again if I have misunderstood the problem.

**Comment by fnielsen** [comment]
I have relinked them now https://www.wikidata.org/wiki/Special:WhatLinksHere/Q25304899
