### ISSUE TITLE
Reactome pathway profiles are not rendered correctly 

### ISSUE THREAD

**Issue by lubianat** [WDscholia/scholia#1979]
**Describe the bug**
Reactome pathways are modelled differently from WikiPathways on Wikidata .

Currently the example queries for https://scholia.toolforge.org/pathway/Q50294491 display no results

**To Reproduce**
1. Go to [https://scholia.toolforge.org/pathway/Q50294491](https://scholia.toolforge.org/pathway/Q50294491)
4. See empty queries

**Expected behavior**
Seeing something similar to  profiles for WikiPathways https://scholia.toolforge.org/pathway/Q30225516

(maybe @egonw can help there?)

**Comment by egonw** [comment]
cc @andrawaag

**Comment by andrawaag** [comment]
_"Reactome pathways are modelled differently from WikiPathways on Wikidata "_

That is correct and a deliberate design choice by both the WIkipathways and Reactome development teams. Wikipathways bases it pathways on the Pathway ontology and Reactome on the Gene Ontology. 
I guess fixing this is done by extending the Scholia queries with the Reactome model.

Reactome's schema in Wikidata is described at: https://www.wikidata.org/wiki/EntitySchema:E39

Wikipathways schema in Wikidata is described at: https://www.wikidata.org/wiki/EntitySchema:E41
