### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1990]
From Eric Branson:

Is dark mode available?[1][2] Google has even begun honoring the dark mode user agent preference on Search.[3] I'm not very knowledgeable in this area but I used the <meta> tag on my personal website and it seems to work, even on iOS.[2] I understand that SVG images can also be styled using CSS media queries (to reverse colors, but also adding filters to subdue bright colors, etc.). Dark mode is a huge benefit when working in the dark, so I think user agent preferences should be honored on Scholia. I am not proficient enough with Git or GitHub to create an issue but I can try, if needed. 😂

 Depending on whether the operating system is set to dark or light mode, the whole page appears light on dark, or vice versa, based on the user agent stylesheet. There is no additional developer-provided CSS involved to change the paragraph text or the background color of the page.[1]

[1] https://web.dev/color-scheme/#the-color-scheme-meta-tag
[2] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name
[3] https://9to5google.com/2022/02/21/google-search-black-theme/

**Comment by fnielsen** [comment]
Is this actually possible when we have iframes?

**Comment by carlinmack** [comment]
we can use CSS's `filter: invert(100%);` which produces the following

![image](https://user-images.githubusercontent.com/6676843/173683238-3a3d28ad-9c3e-4b3a-85c9-60d6d20ae067.png)

not perfect but maybe preferable?

**Comment by carlinmack** [comment]
btw covid caught me so I don't expect I'll be contributing in the next few days
