### ISSUE TITLE
Add support for citing software

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1991]
**Is your feature request related to a problem? Please describe.**

We have support for exporting citations from the /works/ aspect, which works mostly fine for journal articles and somewhat for books:
https://scholia.toolforge.org/work/Q21146099/export 

We currently do not have an equivalent for the /software/ aspect, i.e.
https://scholia.toolforge.org/software/Q60565843/export 
does at present not yield anything.

**Describe the solution you'd like**
Pages of the format
https://scholia.toolforge.org/software/{QID}/export 
should provide information suitable for citing software.
Ideally, this would
- improve on the rather scarce information available for software items via the export from the /work/ aspect, e.g. https://scholia.toolforge.org/work/Q60565843/export 
- be compatible with the Software Citation Principles, as per https://doi.org/10.7717/peerj-cs.214

**Additional context**

Design the workflow such that it can
- be readily extended to other research outputs, e.g. data or material resources
- take into account versioning of the cited resource (as well as identifiers of Wikidata dumps)
- display preferred/ canonical citations (e.g. journal articles describing software) next to the citation of the software itself
- provide the citation in a variety of 
  - citation formats, including
    - those already supported by Citation.js &mdash; (BibTeX, CFF), BibLaTeX, [RIS](https://en.wikipedia.org/wiki/RIS_(file_format))
    - Formats yet to be implemented: RefWorks, EndNote .enw, Wikimedia cite templates

**Comment by egonw** [comment]
@Daniel-Mietchen, did https://github.com/WDscholia/scholia/pull/1996 implement the full idea? If so, can this issue be closed?

**Comment by Daniel-Mietchen** [comment]
@egonw I think we can close this one because it is a duplicate. I'll leave the other open and comment there on things yet to be done.
