### ISSUE TITLE
Type of work in license aspect

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2020]
[//]: # "==Do not write above this line==
A Scholia aspect is used to profile the target item in a specific way, e.g.
https://scholia.toolforge.org/topic/Q202864
profiles Q202864 (Zika virus) as a topic.
A query within a given aspect is called a panel. Please use the ``Add new aspect ...`` template to propose a new aspect.
==Write below this line=="
**What kind of panel would you like to add to which Scholia aspect?**
Type of work

**What kind of information should the panel provide, and which of the visualization options (e.g. table, bubble chart, map) should it use?**
Table with counts

**Which Wikidata entries would be good candidates to explore such visualizations?**
Q20007257

**Anything else?**
```sparql
PREFIX target: <http://www.wikidata.org/entity/Q20007257>

SELECT
  ?count
  ?type ?typeLabel ?typeDescription
WITH {
  SELECT
    (COUNT(*) AS ?count)
    ?type
 
  WHERE {
    [] wdt:P275 target: ; 
          wdt:P31 ?type .
  }
  GROUP BY ?type
} AS %types
WHERE {
  INCLUDE %types
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
ORDER BY DESC(?count)
```

**Comment by fnielsen** [comment]
From an idea of @egonw

**Comment by Daniel-Mietchen** [comment]
Another thing we could add is compliance with certain standards, e.g. the Open Definition ([demo](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_Invasion_biology&oldid=1659795268#%F0%9F%AA%A3_Works_in_scope_available_under_an_Open_Definition-compliant_license)), though the data modelling for this still needs to be [polished](https://www.wikidata.org/w/index.php?title=User_talk:Daniel_Mietchen&oldid=1659676385#Open_Definition_conformant_license) a bit.
