### ISSUE TITLE
Enter does not work in front page search field

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2033]
**Describe the bug**
Enter does not work in front page search field

**To Reproduce**
1. Go to https://scholia.toolforge.org/
2. Type something in the search field
3. Press enter
4. Nothing happens

**Expected behavior**
Scholia should search.

**Additional context**
Could this be related to https://github.com/WDscholia/scholia/pull/2026 ?

**Comment by fnielsen** [comment]
The deletion of 
```
    $("#searchterm").on("keydown", function (event) {
      switch (event.key) {
        case "Enter":
          handleSearch(this.value);
          break;
        default:
      }
    });
```
could be an issue?

**Comment by carlinmack** [comment]
ah perhaps, in my testing all cases I could generate seemed to work with the select2 handler above those lines. Best to re-instate those lines :)

**Comment by fnielsen** [comment]
"I could not replicate the bug, but this should be the fix"

The problem appeared in Ubuntu Firefox and Chromium. And in both search fields. With your fix it works again.
