### ISSUE TITLE
Empty software version fails quickstatements

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2083]
**Describe the bug**
Empty software version fails quickstatements

**To Reproduce**
1. Go to  https://scholia.toolforge.org/doi/10.21338/NSD-ESS10-2020

Generates
```
        CREATE
	LAST	P31	Q191067
	LAST	Len	"European Social Survey (ESS), Round 10 - 2020"
	LAST	P348	""
	LAST	P356	"10.21338/NSD-ESS10-2020"
	LAST	P577	+2022-01-01T00:00:00Z/9
	LAST	P856	"https://ess-search.nsd.no/en/study/172ac431-2a06-41df-9dab-c1fd8f3877e7"
	LAST	P1476	en:"European Social Survey (ESS), Round 10 - 2020"
	LAST	P2093	"European Social Survey ERIC (ESS ERIC)"	P1545	"1"
```
where https://www.wikidata.org/wiki/Property:P348 (software version) is empty.

**Expected behavior**
The line with an empty software version should not be generated.

**Additional context**
Perhaps an error in https://github.com/citation-js/citation-js? Or our missing update?

**Comment by egonw** [comment]
cc @larsgw
