### ISSUE TITLE
Possible template issue for "Add new panel"?

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2087]
**Describe the bug**

The "Add new panel" template starts with the following content (see also below screenshot):

```
[//]: # "==Do not write above this line==
A Scholia aspect is used to profile the target item in a specific way, e.g.
https://scholia.toolforge.org/topic/Q202864
profiles Q202864 (Zika virus) as a topic.
A query within a given aspect is called a panel. Please use the ``Add new aspect ...`` template to propose a new aspect.
==Write below this line=="
```

**To Reproduce**

**Expected behavior**
I was expecting something that would start with something like `**What kind of panel would you like to add to which Scholia aspect?**`.

**Screenshots**

Unexpected Markdown source in the current "Add new panel" template:

![image](https://user-images.githubusercontent.com/26721/185067796-934558d3-0513-463b-89c6-e964fd586f4c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Brave

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/187791709-96ff8cc2-3a1e-48e8-9eed-88f5261054f2.png)

This does render correctly but I'll improve the formatting so it's more clear :)
