### ISSUE TITLE
Panel listing the retracted articles in a journal

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2088]
**What kind of panel would you like to add to which Scholia aspect?**

A list with the retracted articles. 

**What kind of information should the panel provide, and which of the visualization options (e.g. table, bubble chart, map) should it use?**

A table with results for a query like this:

```sparql
#Title: The most cited retracted articles in some journal
SELECT DISTINCT ?work ?workLabel ?doi (COUNT(DISTINCT ?citing) AS ?citations) WHERE {

  # change the next line to change the journal(s)
  VALUES ?journal { wd:Q2364336 }

  { ?work wdt:P31 wd:Q45182324 . }
  UNION
  { ?work wdt:P793 wd:Q7316896 . }
  UNION
  { ?work wdt:P5824 [] . }
  OPTIONAL { ?citing wdt:P2860 ?work . }
  ?work wdt:P1433 ?journal ; wdt:P356 ?doi .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} GROUP BY ?work ?workLabel ?doi
  ORDER BY DESC(?citations)
  LIMIT 10
```

**Which Wikidata entries would be good candidates to explore such visualizations?**

* https://scholia.toolforge.org/venue/Q2364336

**Comment by egonw** [comment]
@fnielsen, @Daniel-Mietchen, if you think this is a good idea, I will make a patch.

**Comment by fnielsen** [comment]
This is fine.
