### ISSUE TITLE
Add support for more Wiki languages in Works lookup

### ISSUE THREAD

**Issue by lubianat** [WDscholia/scholia#2109]
**What query is this about**
Please provide a link to a Scholia profile and the appropriate section heading and/ or .sparql file.
https://scholia.toolforge.org/work/Q21090025#wikipedia-mentions
https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/work_wikipedia-mentions.sparql
**What change do you propose, and why?**

Add search for more Wikipedias (like pt:wiki) .

**Any other considerations?**

Maybe generate it in a semi-automatic format for e.g. the top 20 wikis by number of entries https://w.wiki/5ij4 . 

If this is something useful, I'd be happy to make the PR.

**Comment by fnielsen** [comment]
It is now running, see, e.g., https://scholia.toolforge.org/work/Q22253877#wikipedia-mentions
