### ISSUE TITLE
Reuse target: in topic_uses.sparql

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#2111]
**Is your feature request related to a problem? Please describe.**

Queries like https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/topic_uses.sparql are using the prefix ```target:``` as a global variable within a given query, so as to facilitate adaptation. In topic_uses.sparql, however, we use {{ q }} twice

![image](https://user-images.githubusercontent.com/465923/193450675-1528a49b-92bc-4f50-8311-069061a4b8ac.png)

**Describe the solution you'd like**
The second use of {{ q }} should be replaced with an expression using ```target:``` .

**Comment by fnielsen** [comment]
Seems to be the one that is fixed with https://github.com/WDscholia/scholia/pull/2112
