### ISSUE TITLE
Reload button gives error

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2115]
**Describe the bug**
With an empty table the reload button gives error

**To Reproduce**
1. Go to https://scholia.toolforge.org/venue/Q96720267
2. Click on "Reload"
3. Error:

"DataTables warning: table id=recently-published-works-table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"

**Expected behavior**
No error. The table should reload.

**Screenshots**
![image](https://user-images.githubusercontent.com/484028/194173589-a565bfb9-01f0-4a1a-be8a-a8af7cf0d5b7.png)

**Comment by carlinmack** [comment]
oh no :( good catch

**Comment by fnielsen** [comment]
I can no longer reconstruct my error..!?
