### ISSUE TITLE
On taxon profile, add panel about taxa co-occurring with the target taxon in the literature

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#2161]
**What kind of panel would you like to add to which Scholia aspect?**

A panel about taxa co-occurring with the target taxon in the literature

**What kind of information should the panel provide, and which of the visualization options (e.g. table, bubble chart, map) should it use?**

- just a list of taxa that co-occur with the target taxon in the literature, optionally with sample papers
- table is fine

[Sample query for Anopheles gambiae](https://query.wikidata.org/#%23title%3A%20Taxa%20that%20co-occur%20with%20the%20target%20taxon%20in%20the%20literature%0APREFIX%20target%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ135237%3E%20%0A%0ASELECT%20%3Fcount%20%28CONCAT%28%22%2Ftopics%2FQ41407%2C%22%2C%20SUBSTR%28STR%28%3Ftopic%29%2C%2032%29%29%20AS%20%3FcountUrl%29%0A%20%20%20%20%20%20%20%3Ftopic%20%3FtopicLabel%20%28CONCAT%28%22%2Ftopic%2F%22%2C%20SUBSTR%28STR%28%3Ftopic%29%2C%2032%29%29%20AS%20%3FtopicUrl%29%0A%20%20%20%20%20%20%20%3Fexample_work%20%3Fexample_workLabel%20%28CONCAT%28%22%2Fwork%2F%22%2C%20SUBSTR%28STR%28%3Fexample_work%29%2C%2032%29%29%20AS%20%3Fexample_workUrl%29%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount%29%20%3Ftopic%20%28SAMPLE%28%3Fwork%29%20AS%20%3Fexample_work%29%20WHERE%20%7B%0A%20%20%20%20%23%20Find%20works%20for%20the%20specific%20queried%20topic%0A%09%20%20%3Fwork%20wdt%3AP921%2F%28%20wdt%3AP31%2a%2Fwdt%3AP279%2a%20%7C%20wdt%3AP361%2B%20%7C%20wdt%3AP1269%2B%29%20target%3A%20.%0A%20%20%20%20%0A%20%20%20%20%23%20Find%20co-occuring%20topics%0A%20%20%20%20%3Fwork%20wdt%3AP921%20%3Ftopic%20.%0A%20%20%20%20%3Ftopic%20wdt%3AP105%20%3Ftaxonrank%20.%0A%20%20%20%20%0A%20%20%20%20%23%20Avoid%20listing%20the%20queried%20topic%0A%20%20%20%20%20%20FILTER%20%28target%3A%20%21%3D%20%3Ftopic%29%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Ftopic%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20%23%20Label%20the%20results%0A%20%20INCLUDE%20%25result%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22%20.%20%7D%20%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29%20%20):

```SPARQL
#title: Taxa that co-occur with the target taxon in the literature
PREFIX target: <http://www.wikidata.org/entity/Q135237> 

SELECT ?count (CONCAT("/topics/Q41407,", SUBSTR(STR(?topic), 32)) AS ?countUrl)
       ?topic ?topicLabel (CONCAT("/topic/", SUBSTR(STR(?topic), 32)) AS ?topicUrl)
       ?example_work ?example_workLabel (CONCAT("/work/", SUBSTR(STR(?example_work), 32)) AS ?example_workUrl)
WITH {
  SELECT (COUNT(?work) AS ?count) ?topic (SAMPLE(?work) AS ?example_work) WHERE {
    # Find works for the specific queried topic
	  ?work wdt:P921/( wdt:P31*/wdt:P279* | wdt:P361+ | wdt:P1269+) target: .
    
    # Find co-occuring topics
    ?work wdt:P921 ?topic .
    ?topic wdt:P105 ?taxonrank .
    
    # Avoid listing the queried topic
      FILTER (target: != ?topic)
  }
  GROUP BY ?topic
} AS %result
WHERE {
  # Label the results
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh" . } 
}
ORDER BY DESC(?count)  
```

**Which Wikidata entries would be good candidates to explore such visualizations?**

- Enhydra lutris https://w.wiki/5uNf 
- Aedes aegypti https://w.wiki/5uNh 
- Lantana camara https://w.wiki/5uNy 

**Anything else?**
Ideally, we would have a panel about actual biotic interactions too &mdash; I am in touch with @jhpoelen about potential interactions between [GloBI](https://www.globalbioticinteractions.org/) and Scholia.

**Comment by jhpoelen** [comment]
@Daniel-Mietchen very neat! Thanks for sharing. 

Perhaps we can add a "learn more..." button and launch into a full description (and perhaps visualization) of the taxon-level interactions and their related works.
