### ISSUE TITLE
Create an aspect for ontologies

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#2165]
**What kind of aspect would you like to add to Scholia?**

An aspect about ontologies

**What would be good candidates for visualizations within such an aspect?**

- list of related ontologies, ranked by number of overlapping concepts
- list of publications using the ontology

**Which Wikidata entries would be good candidates to explore such visualizations?**

- https://scholia.toolforge.org/topic/Q135085 (Gene Ontology)

**Which of the existing aspects could or should link to or from this new aspect?**

- topic
- use

**Anything else?**
We should keep related concepts in mind here, e.g. schemas, controlled vocabularies, thesauri and such

**Comment by egonw** [comment]
I'll take this one, if you're not working on it yet?

**Comment by Daniel-Mietchen** [comment]
Go for it!

**Comment by andrawaag** [comment]
@egonw pointed me to this. What does it mean that this is closed? Does this aspect call all facets of ontologies? I.e. ontology status, funding, heritage, builds on?

**Comment by egonw** [comment]
> @egonw pointed me to this. What does it mean that this is closed? Does this aspect call all facets of ontologies? I.e. ontology status, funding, heritage, builds on?

Next step is to populate the aspect with panels showing interesting from data in Wikidata. Maybe we start with a data panel listing the maintainers of the ontology or so? For each panel we can create a separate issue (and tag it with the `panels` label).

**Comment by fnielsen** [comment]
@andrawaag It is here: https://scholia.toolforge.org/ontology/ and there is not much at the moment. 

How would we do "list of related ontologies, ranked by number of overlapping concepts" with the current information in Wikidata. Could we do a federated query to some other place?
