### ISSUE TITLE
Typo in cito page

### ISSUE THREAD

**Issue by dpriskorn** [WDscholia/scholia#2188]
![image](https://user-images.githubusercontent.com/68460690/204163706-7cd7d46b-34d5-450c-920b-9775a132bf4a.jpeg)

**Comment by egonw** [comment]
That was fixed in a PR that will lined up: https://github.com/WDscholia/scholia/commit/2e7d3c2740c0023d29beb9a9e6097635f777523b

**Comment by fnielsen** [comment]
Not entirely sure I understood this. "CiTO" seems to be the correct way: https://sparontologies.github.io/cito/current/cito.html

**Comment by egonw** [comment]
It was that CiTO and different were swapped. But in the https://github.com/WDscholia/scholia/commit/2e7d3c2740c0023d29beb9a9e6097635f777523b patch I actually solved it differently.
