### ISSUE TITLE
OJS does not scrape for atla

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2193]
**Describe the bug**

**To Reproduce**
1. `$ python -m scholia.scrape.ojs issue-url-to-quickstatements https://serials.atla.com/proceedings/issue/view/261`
2. No output

**Expected behavior**
It should output quickstatements.

**Comment by DaxServer** [comment]
This issue seem to have already been fixed by this commit https://github.com/WDscholia/scholia/commit/ba8371cdb1e62bd9f5dcdc36acef9b010e6fe7db I was able to import them https://www.wikidata.org/w/index.php?title=Q124317034&oldid=2057514244

**Comment by fnielsen** [comment]
Yes, it seems to be fixed.
