### ISSUE TITLE
I think the ack section can use a revisit?

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2199]
See https://github.com/WDscholia/scholia/blob/b0b286f6ce1ae73ff9389514a237226a8cc4fb76/scholia/app/templates/about.html#L33-L47 which seems outdated

**Comment by fnielsen** [comment]
What are the concrete changes you would like?

**Comment by egonw** [comment]
I think @Daniel-Mietchen follow grants could me mentioned? I can be removed, I guess? Maybe list people that have contributed in the past 2 years, etc.

**Comment by Daniel-Mietchen** [comment]
I'll take a look and suggest some changes.
