### ISSUE TITLE
should the author curator page list author disambiguation for name variants with zero uses?

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2212]
## Context
Currently, the [author curation page](https://scholia.toolforge.org/author/Q20895241/curation) lists author names that are not actually used by article:

![image](https://user-images.githubusercontent.com/26721/210062527-2007b233-39bd-448b-b664-5f9eb92acb2b.png)

## Question
Should the "count = 0" not be omitted?

**Comment by Daniel-Mietchen** [comment]
I think we should leave it in - otherwise, the user does not know which strings have been checked.
