### ISSUE TITLE
When creating items from arXiv, P820 should be used as a qualifier

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#2232]
**Describe the bug**

As originally reported [here](https://www.wikidata.org/w/index.php?title=Topic:Xbgvfahhtgl401rk), Scholia's import workflow from arXiv creates items in which arXiv classification ([P820](https://www.wikidata.org/wiki/Property:P820)) is at statement level, even though its property scope ([P2302](https://www.wikidata.org/wiki/Property:P2302)) [is](https://www.wikidata.org/w/index.php?title=Property:P820&oldid=1784953574#P2302) "qualifier".

**To Reproduce**
1. Check out recent arXiv papers (e.g. via [this query](https://arxiv.org/search/advanced?advanced=&terms-0-operator=AND&terms-0-term=climate&terms-0-field=title&classification-physics_archives=all&classification-include_cross_list=include&date-filter_by=past_12&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=50&order=-announced_date_first)), pick one that looks suitable for Wikidata and copy its arXiv ID
1. Paste that arXiv ID into https://scholia.toolforge.org/arxiv-to-quickstatements and hit the "Extract metadata" button
1. Check the resulting QuickStatements: P820 shows up several lines below P818

**Expected behavior**
arXiv classification ([P820](https://www.wikidata.org/wiki/Property:P820)) should be a qualifier to arXiv ID ([P818](https://www.wikidata.org/wiki/Property:P818)) and thus on the same line as P818 in the QuickStatements commands

**Comment by fnielsen** [comment]
I do not understand why it should be a qualifier and asked a question at https://www.wikidata.org/wiki/Property_talk:P820

**Comment by fnielsen** [comment]
"See [this item](https://www.wikidata.org/wiki/Q14558831) where I use P820 both as qualifier and "main property"." I do not understand: The user hasn't edited https://www.wikidata.org/w/index.php?title=Q14558831&action=history and the identifier was not used as a main property. I seems as if you user both wanted it as a main property and as a qualifier.

**Comment by fnielsen** [comment]
This was a duplicate of https://github.com/WDscholia/scholia/issues/321
