### ISSUE TITLE
As a user I would like to see publications with cito citations on the cito page so I can easily find them

### ISSUE THREAD

**Issue by dpriskorn** [WDscholia/scholia#2252]
**Is your feature request related to a problem?**
I don't know how to find the articles that have these citations. 

**Describe the solution you'd like**
Add a new query for works with at least one cito citation and sort the output to show the most recent first. 

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/68460690/219774054-59cc883c-035f-4731-8e17-dbba5fe206f5.png)

**Comment by egonw** [comment]
I have a patch lined up to implement something in this direction: https://github.com/WDscholia/scholia/pull/2238

**Comment by fnielsen** [comment]
https://scholia.toolforge.org/cito

**Comment by fnielsen** [comment]
https://scholia.toolforge.org/cito/#recent-articles

**Comment by dpriskorn** [comment]
Wohoo 🥳
