### ISSUE TITLE
images for works?

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#226]
@fnielsen, have you considered images for works' main subjects? With a query like:

```sparql
#defaultView:ImageGrid
SELECT DISTINCT ?image WHERE {
  wd:{{ q }} wdt:P921/wdt:P18 ?image .
} 
```

**Comment by fnielsen** [comment]
We have images now, e.g., https://scholia.toolforge.org/work/Q118130164#associated-images.

The query is broader.

**Comment by fnielsen** [comment]
Why is it missing on this page: https://scholia.toolforge.org/work/Q18507561

**Comment by fnielsen** [comment]
Making a new issue: https://github.com/WDscholia/scholia/issues/2438
