### ISSUE TITLE
Workshops should be handled as events

### ISSUE THREAD

**Issue by WolfgangFahl** [WDscholia/scholia#2262]
**Is your feature request related to a problem? Please describe.**
[The 2nd Text2KG](https://scholia.toolforge.org/topic/Q116982157) is shown as a topic

**Describe the solution you'd like**
it should be handled as an event

**Comment by WolfgangFahl** [comment]
This was only temporary - seems like there was a lag in the wikidata update that might have caused the instanceof not being available yet.

**Comment by fnielsen** [comment]
This was likely a cache issue.
