### ISSUE TITLE
Improve support for patents

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#2278]
**Is your feature request related to a problem? Please describe.**

Patents are a part of the landscape Scholia tries to profile, yet it does not currently display patent-related information in a very useful fashion. This was not much of a problem when we had few patent items, but now their numbers are growing.

**Describe the solution you'd like**

Use sample items like [Q118062753](https://scholia.toolforge.org/topic/Q118062753) and its authors to check how patents show up on work, author or topic profiles and perhaps others, like organization, event or award.

**Describe alternatives you've considered**

The alternative would be to ignore patents.

**Additional context**

WikiProject Patents has a list of recommended statements: https://www.wikidata.org/wiki/Wikidata:WikiProject_Patents/Recommended_statements .

**Comment by fnielsen** [comment]
In the first case we could just let it fall back on the "work" aspect.

**Comment by fnielsen** [comment]
* There is no publication date for https://www.wikidata.org/wiki/Q118062753 
* 'filing' and 'consent' is shown in the time chart.
* I suppose we could add P31 to the top table.

**Comment by fnielsen** [comment]
What is "[Publication of US20200328338A1](https://patents.google.com/patent/US20200328338A1/en)" compared to "[Publication of US11289637B2](https://patents.google.com/patent/US11289637B2/en)"?

**Comment by fnielsen** [comment]
Runing at https://scholia.toolforge.org/Q118062753

**Comment by fnielsen** [comment]
Maybe you want to reopen if the changes are not good enough or make a new issue.
