### ISSUE TITLE
Mismatch - PGF Synthase

### ISSUE THREAD

**Issue by JuliaBatUM** [WDscholia/scholia#2286]
Hey!
In the Prostaglandin and leukotriene metabolism in senescence, when I click on PGF synthase I am redirected to "Peroxiredoxin like 2B" (see link below). This is not correct.
https://pathway-viewer.toolforge.org/embed/WP5122
https://scholia.toolforge.org/protein/Q21126813
Kind regards,
Julia

**Comment by fnielsen** [comment]
This link does not resolve https://scholia.toolforge.org/wikipathways/WP5122 the pathway does not seem to be represented on Wikidata? Or how did you get to that pathway?

The embedded image is not directly represented on Wikidata but on WikiPathways at https://www.wikipathways.org//pathways/WP5122

It is unclear to me whether PGF Synthase is represented on Wikidata:
https://www.wikidata.org/w/index.php?go=G%C3%A5&search=PGF+Synthase

**Comment by fnielsen** [comment]
When I look at https://www.wikidata.org/wiki/Q21126813 it seems that "Peroxiredoxin like 2B" is set with an alias "prostamide/PGF synthase". 

In UNIPROT at https://www.uniprot.org/uniprotkb/Q8TBF2/entry, "Peroxiredoxin-like 2B" is an alternative name. So it seems to be ok.

**Comment by JuliaBatUM** [comment]
Hi,

Sorry, my bad! I further checked and indeed Peroxiredoxin like 2B is an alias of PGF synthases. However, I still have a question. When I click on PGF synthase, I am redirected to a protein, while when I click on other enzymes e.g. PGI synthase or TxA synthase I am redirected to a gene. Is this on purpose? And I can´t find any identifiers for PGF synthase. Is it possible to add some?

Thank you and have a nice weekend,

Julia Bous


https://pathway-viewer.toolforge.org/embed/WP5122

________________________________
Von: Finn Årup Nielsen ***@***.***>
Gesendet: Donnerstag, 11. Mai 2023 20:26:41
An: WDscholia/scholia
Cc: Bous, Julia (MACSBIO); Author
Betreff: Re: [WDscholia/scholia] Mismatch - PGF Synthase (Issue #2286)


When I look at https://www.wikidata.org/wiki/Q21126813 it seems that "Peroxiredoxin like 2B" is set with an alias "prostamide/PGF synthase".

In UNIPROT at https://www.uniprot.org/uniprotkb/Q8TBF2/entry, "Peroxiredoxin-like 2B" is an alternative name. So it seems to be ok.

**Comment by fnielsen** [comment]
@JuliaBatUM 

I think you need to go over at Wikipathways and fix it there if there is any problem:
https://www.wikipathways.org/pathways/WP5122.html

@egonw is one of the authors of the pathway. Perhaps he knows something.

**Comment by egonw** [comment]
hi @JuliaBatUM, @fnielsen, yes, I'll pick this up.

Julia, thanks for bringing this up. I will work this out with you. I will check the full thread as soon as possible.

**Comment by egonw** [comment]
Hi @JuliaBatUM, apologies for the delay. I have been very busy, I'm afraid. The analysis above by @fnielsen is correct. Not obvious, but gene/protein names often are not.

About whether it links to the gene or the protein, that depends on the identifier that the author(s) of the pathway have used. In this case, I see this:

![image](https://github.com/WDscholia/scholia/assets/26721/62ed6afe-f100-483e-95f4-33e95baf7f3e)

The old website has links to more databases, via a popup:

![image](https://github.com/WDscholia/scholia/assets/26721/f21700d5-9feb-4611-a269-9bb957d7b90d)

We are discussing how to show all of them (again), but we're not sure how yet, and when we get around to it. 

cc @AlexanderPico @mkutmon
