### ISSUE TITLE
Perhaps announce WikiProject aspect on the Wikidata status update (mailing list)

### ISSUE THREAD

**Issue by carlinmack** [WDscholia/scholia#2293]
## Context
There's a weekly Wikidata newsletter https://www.wikidata.org/wiki/Wikidata:Status_updates

## Question
People involved in Wikidata WikiProjects would be interested in the visualisations we now have. Happy to collaborate on writing it

**Comment by carlinmack** [comment]
cc @Daniel-Mietchen

**Comment by Daniel-Mietchen** [comment]
@carlinmack on it.

**Comment by Daniel-Mietchen** [comment]
@carlinmack [Done](https://www.wikidata.org/w/index.php?title=Wikidata:Status_updates/Next&diff=1927224786&oldid=1926767917&diffmode=source).
