### ISSUE TITLE
how to have an aspect add specific content to the HTML head?

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#232]
Like alternative links for RSS feeds that may apply to a certain aspect? I like to add something like this for author:

    <link rel="alternate" type="application/rss+xml" 
      title="RSS Feed with latest articles of Qxxx" 
      href="/author/Qxxx/latest-works/rss" />

For this, we need aspect-specific content to be (dynamically) embedded in base.html in some way...

**Comment by egonw** [comment]
At the time I did not know that Google (and like other indexers) actually do run JavaScript, so I can just add this line dynamically... Let's hope Feedly does it too :)

**Comment by carlinmack** [comment]
@egonw okay to close?

**Comment by egonw** [comment]
Oh, this is issue is just about the mechanism. Yeah, that's implemented now.
