### ISSUE TITLE
Request cite feature for dataset aspect

### ISSUE THREAD

**Issue by bluerasberry** [WDscholia/scholia#2325]
**Is your feature request related to a problem? Please describe.**
Request "cite" feature for "instance of = dataset", similar to the cite feature for "instance of = software"

**Describe the solution you'd like**
The "cite" button appears on Scholia profiles for software

Any minimal functionality is useful, including title, date of publication, author, publisher, and URL of resource. Support for DOIs. I am not sure that things like version make sense for datasets yet.

**Describe alternatives you've considered**
The alternative is that I generate citations myself.

**Additional context**
Example of software which has a cite button - https://scholia.toolforge.org/software/Q1659584
Example of a dataset which lacks the cite button - https://scholia.toolforge.org/dataset/Q120320769

**Comment by egonw** [comment]
@bluerasberry, did you make a patch yet?
