### ISSUE TITLE
The literature related panels in the `chemical` aspect could link to the `topic` aspect

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2355]
While users are directed to the `Topic` aspect at the top of the page, it would be nice to remind the users of this aspect in the `Recent literature` and `Publications per year` aspects too. Right now, there is no such description:

![image](https://github.com/WDscholia/scholia/assets/26721/eca1fd91-2be2-4fe8-b5ad-0553c134a787)

**Describe the solution you'd like**
I like to add a short text, just below the panel header to remind readers of the `topic` aspect: "More information about literature about this chemical can be found at XXXX", where the last is the link to the matching `topic` aspect.

@fnielsen, what do you think? Good idea?

**Comment by fnielsen** [comment]
Yes. There are some other places where a reminder could be in place - perhaps.
