### ISSUE TITLE
Possible lack of symmetry in taxon - chemical 

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2367]
**Describe the bug**
Possible lack of symmetry in taxon - chemical 

**To Reproduce**
http://127.0.0.1:8100/taxon/Q1000370 Pinales has [Phoeniceroside](http://127.0.0.1:8100/Q105030048) as a metabolome but http://127.0.0.1:8100/chemical-class/Q105030048 has no taxa [Taxa in which the chemical class was found](http://127.0.0.1:8100/chemical-class/Q105030048#found-in-taxon)

**Expected behavior**
Sholdn't it be symmetric?

**Comment by fnielsen** [comment]
See also https://github.com/WDscholia/scholia/pull/2334

**Comment by Adafede** [comment]
http://127.0.0.1:8100/chemical/Q105030048 returns http://127.0.0.1:8100/taxon/Q183497 as expected.
It is a `chemical` and not a `chemical class`, I think the issue is rather the more to `chemical-class`.

**Comment by fnielsen** [comment]
Instead of `?chemical wdt:P279+ target:` it could be `?chemical wdt:P279* target:`
