### ISSUE TITLE
DOI with square brackets is not working in the Scholia search field.

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2406]
**Describe the bug**
https://academic.oup.com/bioscience/article/52/1/44/291662 has a "10.1641/0006-3568(2002)052[0044:PTLBTR]2.0.CO;2".

**To Reproduce**
1. Go to https://scholia.toolforge.org/
2. Click on copy-paste 10.1641/0006-3568(2002)052[0044:PTLBTR]2.0.CO;2 in the search field
3. "DOI does not exist"

**Expected behavior**
The DOI exists and quickstatements should be generated

**Comment by fnielsen** [comment]
Would "{ forceType: '@doi/id' }" be too broad?

**Comment by larsgw** [comment]
On the `https://scholia.toolforge.org/doi/...` page I think it might be expected that the input is treated as a DOI.

**Comment by fnielsen** [comment]
@larsgw I get: 
```
TypeError: No synchronous parser found for @else/url
    data http://127.0.0.1:8100/static/js/citation.js:1264
    chain http://127.0.0.1:8100/static/js/citation.js:933
    <anonymous> else/list+object@http://127.0.0.1:8100/static/js/citation.js:1250
    data http://127.0.0.1:8100/static/js/citation.js:1262
    chain http://127.0.0.1:8100/static/js/citation.js:933
    add http://127.0.0.1:8100/static/js/citation.js:201
    set http://127.0.0.1:8100/static/js/citation.js:222
    Cite http://127.0.0.1:8100/static/js/citation.js:116
    <anonymous> http://127.0.0.1:8100/doi/10.1641/0006-3568(2002)052[0044:PTLBTR]2.0.CO;2:391
[0006-3568(2002)052[0044:PTLBTR]2.0.CO;2:406:13](http://127.0.0.1:8100/doi/10.1641/0006-3568(2002)052%5B0044:PTLBTR%5D2.0.CO;2)
```

**Comment by larsgw** [comment]
I forgot about that... I'm working on it, sorry.

**Comment by larsgw** [comment]
I've ended up broadening the DOI pattern in Citation.js anyway.
