### ISSUE TITLE
Aspect around podcasts

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2414]
**What kind of aspect would you like to add to Scholia?**

Scholia URLs are in the form:

* podcast: https://scholia.toolforge.org/podcast/Q124262264
* podcast season: http://scholia.toolforge.org/podcast-season/Q116869651
* podcast episode: http://scholia.toolforge.org/podcast-episode/Q67590634

A query within a given aspect is called a panel. Please use the ``Add new panel to ... aspect ...`` template to propose a new panel for an aspect.

**Which Wikidata entries would be good candidates to explore such visualizations?**

See above, and https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Podcasts

**Which of the existing aspects could or should link to or from this new aspect?**

Podcasts have links to particularly topics (discussed), presenters, and geusts.

**Comment by fnielsen** [comment]
https://scholia.toolforge.org/podcast/Q2856113

**Comment by fnielsen** [comment]
Also linked from Synia https://synia.toolforge.org/#podcast/Q2856113
