### ISSUE TITLE
Website link shows up on the middle of the page in dataset aspect

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2421]
**Describe the bug**

**To Reproduce**
1. Go to https://scholia.toolforge.org/dataset/Q124340753
2. View https://huggingface.co/datasets/roneneldan/TinyStories below the identifiers table

**Expected behavior**
A link should be placed more "appropriately".

**Comment by faresh9** [comment]
is it good to place it to the right of the title ?

**Comment by fnielsen** [comment]
Below the title on in a table, see also https://scholia.toolforge.org/author/Q18618629
