### ISSUE TITLE
Top-level configurable

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2429]
**Is your feature request related to a problem? Please describe.**
This is related to the ongoing developments around splits and integration with the UIs for queries, like WDQS.

See also:

* https://github.com/WDscholia/scholia/issues/2412
* https://github.com/egonw/scholia/commit/20152877efed739abf4c433bd38e3646371d51aa
* https://github.com/egonw/scholia/commits/exploration/qlever/

**Describe the solution you'd like**
We need in both Python and JavaScript global URLs for the following things:

* run a SPARQL remotely and get the results table back (used for aspect tables)
* link to the QS to embed graphics in the `iframe`
* link to the QS to edit (and run) the SPARQL there

I think these three templates need to have a paramater (like `$sparql`) where the encoded SPARQL is embedded.

**Describe alternatives you've considered**
The current solution is to have these URL patterns hardcoded all over the place. This makes it hard to maintain and update Scholia for other endpoints (like Qlever).

**Comment by egonw** [comment]
@fnielsen, @Daniel-Mietchen, please let me know what you think a patch to do this should take into account.

**Comment by fnielsen** [comment]
Yes. Long time ago we an issue or PR.

**Comment by egonw** [comment]
> Yes. Long time ago we an issue or PR.

@fnielsen, can you help me out? I can find the following related queries, but none capture this issue (fully):

* https://github.com/WDscholia/scholia/issues/2250
* https://github.com/WDscholia/scholia/issues/2063
* https://github.com/WDscholia/scholia/issues/1774

**Comment by fnielsen** [comment]
Yes. I think it would be fine with a configuration. I have previously used the config module: https://github.com/fnielsen/brede/blob/master/brede/config.py
