### ISSUE TITLE
Wrong volume and pages when creating item from DOI

### ISSUE THREAD

**Issue by Robot8A** [WDscholia/scholia#2457]
**Describe the bug**
Scholia created via quickstatements a Wikidata item with wrong volume and pages (it looks like some undesired interaction with having commas in some field):
https://www.wikidata.org/w/index.php?title=Q125401289&oldid=2124720429

**To Reproduce**
1. I went to scholia.toolforge.org
2. I searched 10.2312/EURORV3.20181141 DOI at the search bar
3. I clicked Submit to Quickstatements
4. I created the item

**Expected behavior**
The metadata gets correctly interpreted

**Screenshots**

**Desktop (please complete the following information):**
Unrelated

**Smartphone (please complete the following information):**
Unrelated

**Additional context**
Now that the item is created, searching it again will not reproduce it, but I assume it may happen again with other DOIs from the same venue: 10.2312/eurorv3.20181142, 10.2312/eurorv3.20181143, 10.2312/eurorv3.20181144, 10.2312/eurorv3.20181145

**Comment by fnielsen** [comment]
Crossref API says "Resource not found"!

`curl -X 'GET' 'https://api.crossref.org/works/10.2312%2FEURORV3.20181141' -H 'accept: application/json'`

**Comment by fnielsen** [comment]
This seems not to be a Scholia problem, but one from the source.

https://citation.crosscite.org/format?doi=10.2312%2FEURORV3.20181142&style=apa&lang=en-US

I am not entirely sure who is making the error.
