### ISSUE TITLE
Show 'reply to' (P2675) relationships

### ISSUE THREAD

**Issue by pigsonthewing** [WDscholia/scholia#249]
https://www.wikidata.org/wiki/Q28951838 is a formal response to https://www.wikidata.org/wiki/Q28951786 as stated in the value of the former's P2675 - yet that relationship is not apparent from either https://tools.wmflabs.org/scholia/work/Q28951838 nor https://tools.wmflabs.org/scholia/work/Q28951786

We might also need to do this for 'inspired by' (P941).

**Comment by fnielsen** [comment]
Yes, we need to show a lot of "direct" information for the works.
