### ISSUE TITLE
Incorrect linking of literature to topics

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#2544]
**Describe the bug**
When I look at the page for [ELIXIR Europe](https://www.wikidata.org/wiki/Q12269561), an organization that exists for a bit over 10 years, then the `/topic/` page should not include literature from the 14th century:

![image](https://github.com/user-attachments/assets/0b29f253-ba53-4bc3-9e3a-4731f9d5e882)

**To Reproduce**
1. Go to https://scholia.toolforge.org/topic/Q12269561
2. Scroll down to "[Publications per year](https://scholia.toolforge.org/topic/Q12269561#publications-per-year)"
4. See way too much and too old literature

**Expected behavior**
The plot should show literature that is about ELIXIR Europe.

**Comment by egonw** [comment]
The problem is likely that the ELIXIR nodes are linked to countries which are linked to old literature. I do not know how to address this, but this depiction is not helpful.

**Comment by fnielsen** [comment]
Sapienza University of Rome https://www.wikidata.org/wiki/Q209344#P361 is part of [ELIXIR Italy](https://www.wikidata.org/wiki/Q109496581) which in my ontology in my head is wrong.

**Comment by egonw** [comment]
Thanks.

**Comment by fnielsen** [comment]
I wonder how we should represent these relationships? Should https://www.wikidata.org/wiki/Q1094965 be P1416'ed the Sapiensa University?

**Comment by fnielsen** [comment]
https://www.wikidata.org/w/index.php?title=Q109496581&diff=prev&oldid=2262857515
