### ISSUE TITLE
"Recently retracted works" "Wikidata Query Service" link in work index does not work

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2550]
**Describe the bug**
Link at the bottom left of https://scholia.toolforge.org/work/#recently-retracted-works does not work

**To Reproduce**
1. Go to https://scholia.toolforge.org/work/#recently-retracted-works
2. Click on "Wikidata Query Service" (left bottom)
3. https://query.wikidata.org/%23%20tool%3A%20scholia%0ASELECT%20DISTINCT%0A%20%20%3Fretracted_work%20%3Fretracted_workLabel%20(CONCAT(%22%2Fwork%2F%22%2C%20SUBSTR(STR(%3Fretracted_work)%2C%2032))%20AS%20%3Fretracted_workUrl)%0A%20%20%3Fdate%0A%20%20%3Fretraction%20%3FretractionLabel%20(CONCAT(%22%2Fwork%2F%22%2C%20SUBSTR(STR(%3Fretraction)%2C%2032))%20AS%20%3FretractionUrl)%0AWITH%20%7B%0A%20%20%23%20Find%20retracted%20papers%20indicated%20by%20instance%20of%20retracted%20paper%2C%20%0A%20%20%23%20by%20retraction%20notice%20property%20or%20by%20significant%20event%0A%20%20SELECT%20DISTINCT%20%3Fretracted_work%20WHERE%20%7B%0A%20%20%20%20%7B%20%3Fretracted_work%20wdt%3AP31%20wd%3AQ45182324%20%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%20%3Fretracted_work%20wdt%3AP5824%20%5B%5D%20%7D%0A%20%20%20%20UNION%0A%20%20%20%20%7B%20%3Fretracted_work%20wdt%3AP793%20wd%3AQ45203135%20%7D%0A%20%20%7D%0A%7D%20AS%20%25retracted_works%0AWHERE%20%7B%0A%20%20INCLUDE%20%25retracted_works%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fretracted_work%20wdt%3AP5824%20%3Fretraction%20.%0A%20%20%20%20%3Fretraction%20wdt%3AP577%20%3Fretraction_datetime%0A%20%20%7D%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fretracted_work%20p%3AP793%20%5B%20ps%3AP793%20wd%3AQ45203135%20%3B%20pq%3AP585%20%3Fkeyevent_datetime%20%5D%0A%20%20%7D%0A%20%20BIND(COALESCE(xsd%3Adate(COALESCE(%3Fretraction_datetime%2C%20%3Fkeyevent_datetime))%2C%20%22Unknown%20date%22)%20AS%20%3Fdate)%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20DESC(%3Fdate)%0A
4. See error "Not Found"

**Expected behavior**
The link should work

**Additional context**
Other links work.

**Comment by egonw** [comment]
Also applies to the table at https://scholia.toolforge.org/chemical/

**Comment by fnielsen** [comment]
> Also applies to the table at https://scholia.toolforge.org/chemical/

So it seems to be the index pages only.
