### ISSUE TITLE
Create some "missing" subpage for every aspect

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#281]
E.g. right now we have 
https://tools.wmflabs.org/scholia/author/Q8219/missing
as a complement to 
https://tools.wmflabs.org/scholia/author/Q8219

but no 
https://tools.wmflabs.org/scholia/taxon/Q91703/missing
for
https://tools.wmflabs.org/scholia/taxon/Q91703 .

**Comment by Daniel-Mietchen** [comment]
Would be great if we could use ShEx to help generate such /missing pages.

**Comment by carlinmack** [comment]
I'm planning on closing this in #1561, @Daniel-Mietchen could you elaborate on "Would be great if we could use ShEx to help generate such /missing pages."? I'm not familiar with what ShEx is

**Comment by fnielsen** [comment]
It is a language to define what properties and values and item should have: https://scholia.toolforge.org/topic/Q29377880

Perhaps this explains: https://scholia.toolforge.org/work/Q51613194

**Comment by fnielsen** [comment]
The ShEx are defined in their own namespace, e.g., https://www.wikidata.org/wiki/EntitySchema:E15

**Comment by carlinmack** [comment]
Ah but we would need to do #1446 before we could use them in Scholia right?

**Comment by fnielsen** [comment]
Yes. And even then I am not sure that ShEx could help us to set up all curation

**Comment by Daniel-Mietchen** [comment]
I also doubt whether we can create suitable curation queries solely based on ShEx in all cases.
But I think that we should have a curation page for every aspect, and it would be good to have some streamlining here, similar to how the templates on the talk page of a Wikidata property already provide some basic queries that assist curation.
