### ISSUE TITLE
Add a suitable random button to every aspect

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#284]
E.g. we currently have it at
https://tools.wmflabs.org/scholia/author/
but not at
https://tools.wmflabs.org/scholia/work/ .

**Comment by Daniel-Mietchen** [comment]
Like wise, we have
https://tools.wmflabs.org/scholia/author/random
but not
https://tools.wmflabs.org/scholia/work/random

**Comment by Daniel-Mietchen** [comment]
[Here](https://query.wikidata.org/#SELECT%20%3Fitem%20%0AWHERE%0A%7B%0A%20%20SERVICE%20bd%3Asample%20%7B%20%3Fsamplepub%20wdt%3AP50%20%3Fitem.%20bd%3AserviceParam%20bd%3Asample.limit%201%20%7D%0A%7D%0A%23%20timestamp%20X) is a minimal example of a query that could support a random button:

```SPARQL
SELECT ?item 
WHERE
{
  SERVICE bd:sample { ?samplepub wdt:P50 ?item. bd:serviceParam bd:sample.limit 1 }
}
# timestamp X
```

The ```timestamp X``` part is there to circumvent the WDQS cache and would have to be added via Python or JavaScript, in terms of Unix time or similar.

This setup is easily modifiable for other aspects but I chose author here because that is our current implementation and also discussed in #586 and #1062 .

Depending on how random we would want the button (or variants thereof) to be, we could also add some filtering or prioritizing, e.g. as per [this query variant](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20%3FitemDescription%20%3Fpub%20%3Fst%20%3Fids%20%3Fsl%20%28COUNT%20%28DISTINCT%20%3Fwork%29%20AS%20%3Fpubs%29%0AWHERE%0A%7B%0A%20%20SERVICE%20bd%3Asample%20%7B%20%3Fpub%20wdt%3AP50%20%3Fitem.%20bd%3AserviceParam%20bd%3Asample.limit%2042%20%7D%0A%20%23%20OPTIONAL%20%0A%20%20%7B%20%3Fitem%20wikibase%3Astatements%20%3Fst%20%3B%20wikibase%3Aidentifiers%20%3Fids%20%3B%20wikibase%3Asitelinks%20%3Fsl%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20%3Fwork%20wdt%3AP50%20%3Fitem.%20%0A%7D%0AGROUP%20BY%20%3Fitem%20%3FitemLabel%20%3FitemDescription%20%3Fpub%20%3Fst%20%3Fids%20%3Fsl%20%3Fpubs%0AORDER%20BY%20DESC%28%3Fst%20%2a%20%3Fpubs%20%2a%20%28%3Fsl%20%2B%201%29%20%2a%20%28%3Fids%20%2B%201%20%29%29%0A%23LIMIT%201%0A):

```SPARQL
SELECT ?item ?itemLabel ?itemDescription ?pub ?st ?ids ?sl (COUNT (DISTINCT ?work) AS ?pubs)
WHERE
{
  SERVICE bd:sample { ?pub wdt:P50 ?item. bd:serviceParam bd:sample.limit 42 }
 # OPTIONAL 
  { ?item wikibase:statements ?st ; wikibase:identifiers ?ids ; wikibase:sitelinks ?sl }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?work wdt:P50 ?item. 
}
GROUP BY ?item ?itemLabel ?itemDescription ?pub ?st ?ids ?sl ?pubs
ORDER BY DESC(?st * ?pubs * (?sl + 1) * (?ids + 1 ))
#LIMIT 1

```

**Comment by fnielsen** [comment]
The current hack in `random_author` is reasonably fast, and can also be used for works.
