### ISSUE TITLE
From Topic aspects, link to Reasonator and SQID

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#286]
i.e. from
https://tools.wmflabs.org/scholia/topic/Q202864
to
https://tools.wmflabs.org/reasonator/?q=Q202864
and 
https://tools.wmflabs.org/sqid/#/view?id=Q202864

**Comment by Daniel-Mietchen** [comment]
As of [today](https://twitter.com/MagnusManske/status/1039439994354655232), Reasonator links to Scholia, so linking back makes even more sense now.

**Comment by fnielsen** [comment]
With Reasonator and Der Magnus linking to Scholia we have reached Nirvana and I see no need to develop Scholia any further.
