### ISSUE TITLE
In Taxon aspect, provide list of identifiers that the taxon has

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#297]
[This query](https://query.wikidata.org/#SELECT%20%3FID%20%3Flabel%20WHERE%20%7B%0A%20%20%3FID%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ42396390.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%0A%20%20%20%20%3FID%20rdfs%3Alabel%20%3Flabel%0A%20%20%7D%0A%20%20%0A%7D%0A) lists all taxon identifier properties (currently 81):

```SPARQL

SELECT ?ID ?label WHERE {
  ?ID wdt:P31/wdt:P279* wd:Q42396390.
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" . 
    ?ID rdfs:label ?label
  }
  
}

```

Pinging #290 for tracking progress on taxon aspect.

**Comment by fnielsen** [comment]
I suppose this is implemented with #1164
