### ISSUE TITLE
Fail more gracefully when a query yielded no results

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#301]
e.g. the "Co-occurring topics map" panel in
https://tools.wmflabs.org/scholia/topic/Q12626253
is not very useful.
Once the query has run &mdash; and Scholia thus knows (without caching, as per #67) that it had no results &mdash; the current "Unable to display result" panel should probably replaced with a statement like 
> This query yielded no results. You can still try to find something by [modifying  it](https://query.wikidata.org/#%23defaultView%3AMap%0ASELECT%0A%20%20%3Flocation%20%3FlocationLabel%0A%20%20%3Fgeo%0A%20%20%3Fexample_work%20%3Fexample_workLabel%0AWITH%20%7B%0A%20%20SELECT%0A%20%20%20%20%3Flocation%20%3Fgeo%0A%20%20%20%20%28SAMPLE%28%3Fwork%29%20AS%20%3Fexample_work%29%0A%20%20WHERE%20%7B%0A%20%20%20%20%23%20Find%20works%20that%20are%20marked%20with%20main%20subject%20of%20the%20topic.%0A%20%20%20%20%3Fwork%20wdt%3AP921%20%2F%20%28%20wdt%3AP31%2a%2Fwdt%3AP279%2a%20%7C%20wdt%3AP361%2B%20%7C%20wdt%3AP1269%2B%20%29%20wd%3AQ12626253%20.%0A%20%20%20%20%0A%20%20%20%20%23%20Identify%20co-occuring%20topic%20that%20is%20geo-locatable.%20%0A%20%20%20%20%3Fwork%20wdt%3AP921%20%3Flocation%20.%0A%20%20%20%20%3Flocation%20wdt%3AP625%20%3Fgeo%20.%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Flocation%20%3Fgeo%0A%7D%20AS%20%25results%0AWHERE%20%7B%0A%20%20INCLUDE%20%25results%0A%20%20%0A%20%20%23%20Label%20the%20results%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22.%0A%20%20%7D%0A%7D%0A).

**Comment by Daniel-Mietchen** [comment]
We looked into this today, and it seems that due to the iframe embedded from an external domain (wikidata,org), JavaScript on the Scholia end cannot access the error message to modify the display.

Pinging @lucaswerkmeister to take a look at this from the Wikidata end.

**Comment by lucaswerkmeister** [comment]
Hm, yes, it looks like Scholia isn’t allowed to access anything in the embedded IFrames. That’s annoying.

The windows can exchange messages using [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) (Scholia → WDQS via `iframe.contentWindow`, or WDQS → Scholia via `window.parent`), but for that we need to figure out which messages they can exchange that will be useful not only to Scholia, but also to other WDQS embedders.

**Comment by maxlath** [comment]
reporting on the hacky solution I envisioned:

## idea
* setting up a simple proxy running on tools.wmflabs.org which would proxy requests to the query service embed endpoint
* from this proxy, drop all cookies and restrictive security + add CORS headers

## pitfall
* it does work: [you still can't edit an iframe it appears](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow), whatever the HTTP headers :/

## conclusion
yep, bubbling this issue to query.wikidata.org looks like a good solution (otherwise I can offer ideas on running the embedded page in a headless browser to get it fully rendered and edit the html before adding it to a DOM node... feeling dirty now)

**Comment by fnielsen** [comment]
In the long tem wouldn't it be better to implement the rendering on Scholia itself. This way queries does not have to be redundant.

**Comment by Daniel-Mietchen** [comment]
I opened a new ticket for doing the rendering on our end: https://github.com/fnielsen/scholia/issues/394 .
Would still nice to have an interim solution though.
