### ISSUE TITLE
CMLRSS extension for the /venue/ aspect

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#346]

**Comment by egonw** [comment]
I have give this some thought, and basically the aspects do not have sections where I think this makes a lot of sense... one exception is the journal level, where you wish to monitor which compounds a journal publishes about...

**Comment by egonw** [comment]
The CMLRSS feed would also be interesting for /chemical-class/, I realized this afternoon...

**Comment by Daniel-Mietchen** [comment]
@egonw any updates on this?

**Comment by egonw** [comment]
Too complex for Scholia. Closing this for now.

**Comment by fnielsen** [comment]
What was this? It is not "Camless piston engine". Cellular and Molecular Life Sciences?

**Comment by egonw** [comment]
https://scholia.toolforge.org/work/Q27093408
