### ISSUE TITLE
HTML titles for SEO

### ISSUE THREAD

**Issue by dartar** [WDscholia/scholia#524]
I just noticed that all pages in Scholia use the same HTML title. Adding meaningful HTML titles using the item label is a simple fix that's guaranteed to drive traffic and discoverability. 

You could format them in the following ways:

## Label only

 - Scholia: Denny Vrandečić
 - Scholia: Technical University of Denmark

## Label and QID

 - Scholia: Denny Vrandečić (Q18618629)
 - Scholia: Technical University of Denmark (Q1269766)

## Facet and label

 - Scholia: Author: Denny Vrandečić 
 - Scholia: Organization: Technical University of Denmark

I'd personally favor 1. Label only or 3. Facet and label. The QID doesn't add anything meaningful to the end user. Exposing the facet in the HTML title could be useful for items that can have multiple aspects.

If you end up implementing it, check how it affects traffic data.

**Comment by nunogit** [comment]
This is very important from a seo and google visibility perspective.
I would add to this: add a meta description.

**Comment by fnielsen** [comment]
Currently, we sent off the page with no server-side lookup for speed. If we need meta-tags we need a server-side look, if it is not possible to set it by Javascript.

**Comment by carlinmack** [comment]
Hi, I think we should set them with Javascript as this will be greatly beneficial for users with many scholia tags. I am going to disagree with the OP on the format though. Here are the 6 tabson BBC News for example
