### ISSUE TITLE
Build author-disambiguator link from aliases

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#608]
Question here: https://stackoverflow.com/questions/53933564
```sparql
SELECT
  (COUNT(?work) AS ?count) 
  ?author_name
  (CONCAT(
      'https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=',
      ENCODE_FOR_URI(?author_name)) AS ?author_disambiguator)
WHERE {
  {
    SELECT DISTINCT ?author_name {
      wd:Q7082930 skos:altLabel ?author_name_ .
      
      # The SELECT-DISTINCT-BIND trick here is due to Stanislav Kralin
      # https://stackoverflow.com/questions/53933564
      BIND (STR(?author_name_) AS ?author_name)
    }
  }
  OPTIONAL { ?work wdt:P2093 ?author_name . }
}
GROUP BY ?author_name 
ORDER BY DESC(?count)

```

**Comment by Daniel-Mietchen** [comment]
Depending on performance, this could be combined with strings that appear as P1932 ("stated as") values in P50 (author) statements, as per https://github.com/Daniel-Mietchen/ideas/issues/488 and https://github.com/arthurpsmith/author-disambiguator/issues/26 .

Note that the author disambiguator allows some additional filtering, as per https://github.com/arthurpsmith/author-disambiguator/issues/17 .

**Comment by Daniel-Mietchen** [comment]
[Here](https://query.wikidata.org/#PREFIX%20target%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ6251482%3E%0A%0ASELECT%0A%20%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount%29%20%0A%20%20%3Fauthor_name%0A%20%20%28CONCAT%28%0A%20%20%20%20%20%20%27https%3A%2F%2Ftools.wmflabs.org%2Fauthor-disambiguator%2F%3Fdoit%3DLook%2Bfor%2Bauthor%26name%3D%27%2C%0A%20%20%20%20%20%20ENCODE_FOR_URI%28%3Fauthor_name%29%29%20AS%20%3Fauthor_resolver_url%29%0AWHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20DISTINCT%20%3Fauthor_name%20%7B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%7B%20target%3A%20skos%3AaltLabel%20%3Fauthor_name_%20%7D%20UNION%20%7B%20target%3A%20rdfs%3Alabel%20%3Fauthor_name_%20%7D.%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%23%20The%20SELECT-DISTINCT-BIND%20trick%20here%20is%20due%20to%20Stanislav%20Kralin%0A%20%20%20%20%20%20%23%20https%3A%2F%2Fstackoverflow.com%2Fquestions%2F53933564%0A%20%20%20%20%20%20BIND%20%28STR%28%3Fauthor_name_%29%20AS%20%3Fauthor_name%29%20%7D%0A%20%20%20%20%20%20UNION%0A%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%3Fauthor_statement%20ps%3AP50%20target%3A%20.%0A%20%20%20%20%20%20%20%20%3Fauthor_statement%20pq%3AP1932%20%3Fauthor_name.%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fwork%20wdt%3AP2093%20%3Fauthor_name%20.%20%7D%0A%7D%0AGROUP%20BY%20%3Fauthor_name%20%0AORDER%20BY%20DESC%28%3Fcount%29%0A) is a variant of that query that uses "stated as" too:

```SPARQL
PREFIX target: <http://www.wikidata.org/entity/Q6251482>

SELECT
  (COUNT(?work) AS ?count) 
  ?author_name
  (CONCAT(
      'https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=',
      ENCODE_FOR_URI(?author_name)) AS ?author_resolver_url)
WHERE {
  {
    SELECT DISTINCT ?author_name {
      {
      { target: skos:altLabel ?author_name_ } UNION { target: rdfs:label ?author_name_ }.
      
      # The SELECT-DISTINCT-BIND trick here is due to Stanislav Kralin
      # https://stackoverflow.com/questions/53933564
      BIND (STR(?author_name_) AS ?author_name) }
      UNION
      { 
        ?author_statement ps:P50 target: .
        ?author_statement pq:P1932 ?author_name.
      }
    }
  }
  OPTIONAL { ?work wdt:P2093 ?author_name . }
}
GROUP BY ?author_name 
ORDER BY DESC(?count)

```

**Comment by fnielsen** [comment]
We have implemented that both from altLabel and from the qualifier.
