### ISSUE TITLE
In country/ topic subaspect, add a panel for organizations

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#681]
e.g. 
https://tools.wmflabs.org/scholia/country/Q30/topic/Q2122243

**Comment by fnielsen** [comment]
We have [Organizations of the country who published on the topics](https://scholia.toolforge.org/country/Q30/topic/Q2122243#organizations).

Implemented last year: https://github.com/WDscholia/scholia/commits/master/scholia/app/templates/country-topic_organizations.sparql

**Comment by fnielsen** [comment]
"Organizations in the country that have published on the topics" is perhaps a better header
