### ISSUE TITLE
Show all authors in list of publications and sorted

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#7]
The list of publications shows only P50-authors, - not P2093-authors. And the authors are not sorted according to P1545.

**Comment by egonw** [comment]
Maybe adding the 'serials ordinal' would be a great start? It would make it clear if authors are missing...

**Comment by Daniel-Mietchen** [comment]
To check for missing authors, I think having/ proposing a dedicated property for "number of authors" would probably be best. Otherwise, it would be hard to notice that the last one(s) are missing.

**Comment by fnielsen** [comment]
There is now a table with "list of authors" that shows both P50 authors and P2093-authors.
