### ISSUE TITLE
DFF Application

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#730]
* https://dff.dk/aktuelt/tematisk-forskning-2019-marts.pdf
* Thematic call in "Digitale teknologier (AI mv.) (FORSK2025)"

2.2.1 Kunstig intelligens og big data
---------------------------------------------
Forskningen kan f.eks. bidrage med viden om opsamling, lagring, transmission og udnyttelse af store
og komplekse datamængder (Big Data), som ofte også vil være kendetegnet ved at komme løbende
eller med stor hastighed. Forskningen kan være generisk såvel som have sektorspecifikke anvendelses-
muligheder.
Forskningen kan f.eks. også bidrage til viden om, hvordan data kan struktureres, lagres og præsenteres,
så det bedst muligt understøtter en menneskelig analyseproces eller hvordan forudsigelser om nye data
kan laves ved brug af modeller baseret på tidligere data f.eks. ved hjælp af machine learning, dynamiske
systemer og stokastiske systemer.
Der kan også forskes i algoritmiske teknikker, udvikling af kunstig intelligens med garanterede sikker-
hedsegenskaber og datamining.

Members
------------
https://tools.wmflabs.org/scholia/authors/Q57419905,Q5268410,Q64055675,Q21264481

Peter Gorm Larsen, Dexter Kozen, Lars Birkedal,Orna Kupferman

**Comment by Daniel-Mietchen** [comment]
> 2.1  ANSØGNINGSFRISTERAlle ansøgninger skal være indsendt i ansøgningssystemet www.e-grant.dk senest tirsdag den 18. juni 2019 kl. 12:00.

Given that this is now more than two years ago, I am closing this ticket.
