### ISSUE TITLE
CZI: "Essential Open Source Software for Science"

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#731]
CZI: "Essential Open Source Software for Science"
* https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/

**Comment by fnielsen** [comment]
"must be released under a permissive open source license (​MIT, BSD 2-Clause, BSD 3-Clause, or Apache v2.0​ )" may be a showstopper because of GPL3

**Comment by Daniel-Mietchen** [comment]
Do we have any pieces of code that have come in under GPL3 and that we cannot put under a different license, or dual-license?

**Comment by fnielsen** [comment]
Not as far as I know. A question is if we want and another is why CZI does not favours GPL.

**Comment by Daniel-Mietchen** [comment]
The call is out: https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/

**Comment by fnielsen** [comment]
"Copyleft license" is now mentioned

**Comment by Daniel-Mietchen** [comment]
They have had four rounds of applications now, and it is still not clear we would fit. Closing.
