### ISSUE TITLE
Close the ICCS Proceedings paper project

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#755]
as per https://github.com/fnielsen/scholia/projects/3

**Comment by egonw** [comment]
I will wrap up this article this summer, and ack Sloan funding.

**Comment by egonw** [comment]
I wanted the Bacting paper published first. This is nearing completion, and then I will finish this paper this summer.

**Comment by Daniel-Mietchen** [comment]
Essentially a duplicate of #464
