### ISSUE TITLE
Look into Dimple

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#758]
As per
https://github.com/fnielsen/scholia/issues/113#issuecomment-302747849 ,
WDQS visualizations are based on http://dimplejs.org/ , which uses https://d3js.org/ .

**Comment by egonw** [comment]
cc @ammar257ammar  (Dimple is a derivative of d3.js)

**Comment by egonw** [comment]
See also Ammar's previous work: https://github.com/ammar257ammar/scholia/blob/flask-cache/scholia/app/templates/iframes/organization.html#L36

**Comment by carlinmack** [comment]
Dimple is no longer under active development, so I think this issue is a deadend

**Comment by Daniel-Mietchen** [comment]
> Dimple is no longer under active development, so I think this issue is a deadend

Agreed. @egonw shall we close it?

**Comment by fnielsen** [comment]
Plotly and nvd3 seems also more elaborate.
