### ISSUE TITLE
Make About link visible from the menu bar directly

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#879]
rather than through the dropdown. This will affect the "Help" and "FAQ" links as well, so let's consider them in context.

**Comment by Daniel-Mietchen** [comment]
This ticket, along with #878 , was triggered by https://en.wikipedia.org/w/index.php?title=Template_talk:Scholia&oldid=922620697 .

**Comment by fnielsen** [comment]
I do not see the point of having the About in the menu bar directly. My Firefox does not have that. Skype does not have it. Thunderbird does not have it.

**Comment by fnielsen** [comment]
I will close this. Please open it if there is a good argument.
