### ISSUE TITLE
In author comparison, add their academic tree

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#888]
Examples for Denny and me (inspired by [his tweet](https://twitter.com/vrandezo/status/1184531396519485440)):
* [Union](https://query.wikidata.org/#%23defaultView%3AGraph%0Aselect%20%0A%3Fadvisor1%20%3Fadvisor1Label%20%3Fimage%20%3Fadvisor2%20%3Fadvisor2Label%0A%7B%0A%7B%20%20wd%3AQ18618629%20wdt%3AP184%2a%20%3Fadvisor1%20.%20%7D%20%0A%20%20UNION%0A%7B%20%20wd%3AQ20895785%20wdt%3AP184%2a%20%3Fadvisor1%20.%20%7D%20%0A%20%20%0A%20%20%3Fadvisor1%20wdt%3AP184%20%3Fadvisor2%20.%0A%20%20optional%20%7B%20%3Fadvisor1%20wdt%3AP18%20%3Fimage%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D)
* [Intersection](https://query.wikidata.org/#%23defaultView%3AGraph%0Aselect%20%0A%3Fadvisor1%20%3Fadvisor1Label%20%3Fimage%20%3Fadvisor2%20%3Fadvisor2Label%0A%7B%0A%7B%20%20wd%3AQ18618629%20wdt%3AP184%2a%20%3Fadvisor1%20.%20%7D%20%0A%23%20%20UNION%0A%7B%20%20wd%3AQ20895785%20wdt%3AP184%2a%20%3Fadvisor1%20.%20%7D%20%0A%20%20%0A%20%20%3Fadvisor1%20wdt%3AP184%20%3Fadvisor2%20.%0A%20%20optional%20%7B%20%3Fadvisor1%20wdt%3AP18%20%3Fimage%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D)

**Comment by carlinmack** [comment]
Duplicate of #675
