### ISSUE TITLE
Externalize SPARQL queries into templates

### ISSUE THREAD

**Issue by cthoyt** [WDscholia/scholia#906]
Since some of the HTML templates have become large due the several embedded SPARQL queries in each, I would propose externalizing them into templates themselves that can be included using the `{% include 'filename.sparql' %}` command. 

I'll make a short PR that shows this works in principle.

**Comment by Daniel-Mietchen** [comment]
Pinging #791 , which is about the same problem but does not propose a concrete solution such as yours.

**Comment by fnielsen** [comment]
Is it a problem that they are too large? Doesn't the extract files increase the complexity?

**Comment by cthoyt** [comment]
Because there are so many SPARQL queries embedded directly in the HTML files, they're quite large and hard to navigate. I think moving them to separate files don't increase complexity by so much. Just in case, I also added an explanation to the CONTRIBUTING.rst in this PR to explain how this kind of Jinja2 templating works.

Overall, this might increase organization and make it a bit less daunting for new contributors

**Comment by Daniel-Mietchen** [comment]
We are keeping track of progress with this via #1267.

**Comment by Daniel-Mietchen** [comment]
All done now.

**Comment by cthoyt** [comment]
@Daniel-Mietchen that's great! I'm glad you were able to use this idea.
