### ISSUE TITLE
disease ID redirects

### ISSUE THREAD

**Issue by egonw** [WDscholia/scholia#924]
What I have in mind is redirects based on disease identifiers (ICD9/ICD10) in Wikidata, just like we have [redirects for compound identifiers](https://tools.wmflabs.org/scholia/chemical/):

![image](https://user-images.githubusercontent.com/26721/69420982-25a66d80-0d20-11ea-9984-332e49231c0b.png)

@fehrhart or @DeniseSl22, are you interested in implementing this?

**Comment by fehrhart** [comment]
You mean, that if someone puts in 601234 in the search window it can recognise this as an OMIM identifier and link to the disease?

**Comment by DeniseSl22** [comment]
Yeah, so it would be omim/number , or orphanet/ID, or umlscui/ID

**Comment by egonw** [comment]
@fehrhart, no, actually, the examples in the screenshots are URL patters, just like @DeniseSl22 indicated, e.g. https://tools.wmflabs.org/scholia/omim/12345
