### ISSUE TITLE
Migrate Python 2.7 code to Python 3

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#952]
as per
https://docs.python.org/3/howto/pyporting.html
and
https://pythonclock.org/ .

**Comment by egonw** [comment]
Did you run into problems? I haven't and have been using Python3 since day one.

**Comment by Daniel-Mietchen** [comment]
I have not noticed any problems yet, but 2.7 is still visible in some corners, e.g. setup.py .
So now seems like a good time to check for such things.

**Comment by fnielsen** [comment]
I have been attempting to write for both 2 and 3. Tox is current (also) testing for py35, so it is already "migrated". The setup.py should be appended though.

**Comment by carlinmack** [comment]
As setup.py was updated in #1329, any other files outstanding?

**Comment by egonw** [comment]
See also https://github.com/WDscholia/scholia/pull/1531

**Comment by fnielsen** [comment]
The syntax error has now been fixed with https://github.com/WDscholia/scholia/commit/f3504d80833745315c6558558698f2478b3c5d56

Nevertheless, I suppose that we could drop Python2.7 support

**Comment by fnielsen** [comment]
Our tox is now testing for Python 3.7, 3.8, 3.9. We are also running Python 3 on the Toolforge.
