### ISSUE TITLE
Document some key changes we've made to Scholia over the course of the project

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#971]
perhaps via a set of tables on a dedicated page, with screenshots and links to particular code snapshots whenever possible.

**Comment by carlinmack** [comment]
difference between this and #964?

**Comment by Daniel-Mietchen** [comment]
964 is about the history of Scholia more generally and setting up some Scholia page for that, whereas this 971 is specifically about the Robustifying project and probably more wiki-centric.

**Comment by Daniel-Mietchen** [comment]
The report has been submitted, and it contains examples of key changes. We'll publish it soon.
